// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: activity_log.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActivityLogEntry contains context associated with a change in the deployment
// history
type ActivityLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,20,opt,name=name,proto3" json:"name,omitempty"`
	// `DELETE` or `SET`
	ActivityType  string                 `protobuf:"bytes,2,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClusterId     *string                `protobuf:"bytes,21,opt,name=cluster_id,json=clusterId,proto3,oneof" json:"cluster_id,omitempty"`
	NamespaceId   string                 `protobuf:"bytes,4,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	NamespaceName string                 `protobuf:"bytes,5,opt,name=namespace_name,json=namespaceName,proto3" json:"namespace_name,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,7,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserEmail     string                 `protobuf:"bytes,8,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	// `route` | `policy` | `settings`
	EntityType  string                        `protobuf:"bytes,9,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId    string                        `protobuf:"bytes,10,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityData  string                        `protobuf:"bytes,11,opt,name=entity_data,json=entityData,proto3" json:"entity_data,omitempty"`
	DiffSummary *ActivityLogEntry_DiffSummary `protobuf:"bytes,12,opt,name=diff_summary,json=diffSummary,proto3" json:"diff_summary,omitempty"`
	// databroker version this change synced to
	DbVersion             uint64   `protobuf:"varint,13,opt,name=db_version,json=dbVersion,proto3" json:"db_version,omitempty"`
	SessionId             string   `protobuf:"bytes,14,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServiceAccountId      string   `protobuf:"bytes,15,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	ImpersonateUserId     string   `protobuf:"bytes,16,opt,name=impersonate_user_id,json=impersonateUserId,proto3" json:"impersonate_user_id,omitempty"`
	ImpersonateUserName   string   `protobuf:"bytes,17,opt,name=impersonate_user_name,json=impersonateUserName,proto3" json:"impersonate_user_name,omitempty"`
	ImpersonateUserEmail  string   `protobuf:"bytes,18,opt,name=impersonate_user_email,json=impersonateUserEmail,proto3" json:"impersonate_user_email,omitempty"`
	ImpersonateUserGroups []string `protobuf:"bytes,19,rep,name=impersonate_user_groups,json=impersonateUserGroups,proto3" json:"impersonate_user_groups,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ActivityLogEntry) Reset() {
	*x = ActivityLogEntry{}
	mi := &file_activity_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityLogEntry) ProtoMessage() {}

func (x *ActivityLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_activity_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityLogEntry.ProtoReflect.Descriptor instead.
func (*ActivityLogEntry) Descriptor() ([]byte, []int) {
	return file_activity_log_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityLogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActivityLogEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActivityLogEntry) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *ActivityLogEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ActivityLogEntry) GetClusterId() string {
	if x != nil && x.ClusterId != nil {
		return *x.ClusterId
	}
	return ""
}

func (x *ActivityLogEntry) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ActivityLogEntry) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

func (x *ActivityLogEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActivityLogEntry) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ActivityLogEntry) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *ActivityLogEntry) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ActivityLogEntry) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ActivityLogEntry) GetEntityData() string {
	if x != nil {
		return x.EntityData
	}
	return ""
}

func (x *ActivityLogEntry) GetDiffSummary() *ActivityLogEntry_DiffSummary {
	if x != nil {
		return x.DiffSummary
	}
	return nil
}

func (x *ActivityLogEntry) GetDbVersion() uint64 {
	if x != nil {
		return x.DbVersion
	}
	return 0
}

func (x *ActivityLogEntry) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ActivityLogEntry) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *ActivityLogEntry) GetImpersonateUserId() string {
	if x != nil {
		return x.ImpersonateUserId
	}
	return ""
}

func (x *ActivityLogEntry) GetImpersonateUserName() string {
	if x != nil {
		return x.ImpersonateUserName
	}
	return ""
}

func (x *ActivityLogEntry) GetImpersonateUserEmail() string {
	if x != nil {
		return x.ImpersonateUserEmail
	}
	return ""
}

func (x *ActivityLogEntry) GetImpersonateUserGroups() []string {
	if x != nil {
		return x.ImpersonateUserGroups
	}
	return nil
}

type GetActivityLogEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityLogEntryRequest) Reset() {
	*x = GetActivityLogEntryRequest{}
	mi := &file_activity_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityLogEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityLogEntryRequest) ProtoMessage() {}

func (x *GetActivityLogEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityLogEntryRequest.ProtoReflect.Descriptor instead.
func (*GetActivityLogEntryRequest) Descriptor() ([]byte, []int) {
	return file_activity_log_proto_rawDescGZIP(), []int{1}
}

func (x *GetActivityLogEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetActivityLogEntryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Entry           *ActivityLogEntry      `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	PreviousEntryId *string                `protobuf:"bytes,2,opt,name=previous_entry_id,json=previousEntryId,proto3,oneof" json:"previous_entry_id,omitempty"`
	NextEntryId     *string                `protobuf:"bytes,3,opt,name=next_entry_id,json=nextEntryId,proto3,oneof" json:"next_entry_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetActivityLogEntryResponse) Reset() {
	*x = GetActivityLogEntryResponse{}
	mi := &file_activity_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityLogEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityLogEntryResponse) ProtoMessage() {}

func (x *GetActivityLogEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityLogEntryResponse.ProtoReflect.Descriptor instead.
func (*GetActivityLogEntryResponse) Descriptor() ([]byte, []int) {
	return file_activity_log_proto_rawDescGZIP(), []int{2}
}

func (x *GetActivityLogEntryResponse) GetEntry() *ActivityLogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *GetActivityLogEntryResponse) GetPreviousEntryId() string {
	if x != nil && x.PreviousEntryId != nil {
		return *x.PreviousEntryId
	}
	return ""
}

func (x *GetActivityLogEntryResponse) GetNextEntryId() string {
	if x != nil && x.NextEntryId != nil {
		return *x.NextEntryId
	}
	return ""
}

// ListActivityLogEntriesRequest defines the types of Activity Log entries to
// list
type ListActivityLogEntriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `DELETE` | `SET`
	ActivityType *string `protobuf:"bytes,1,opt,name=activity_type,json=activityType,proto3,oneof" json:"activity_type,omitempty"`
	NamespaceId  *string `protobuf:"bytes,2,opt,name=namespace_id,json=namespaceId,proto3,oneof" json:"namespace_id,omitempty"`
	UserId       *string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	// `route` | `policy` | `settings`
	EntityType *string `protobuf:"bytes,4,opt,name=entity_type,json=entityType,proto3,oneof" json:"entity_type,omitempty"`
	EntityId   *string `protobuf:"bytes,5,opt,name=entity_id,json=entityId,proto3,oneof" json:"entity_id,omitempty"`
	// `newest` | `oldest` | `from` | `name`
	Query *string `protobuf:"bytes,6,opt,name=query,proto3,oneof" json:"query,omitempty"`
	// list entries starting from an offset in the total list
	Offset *int64 `protobuf:"varint,7,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	// limit the number of entries returned
	Limit *int64 `protobuf:"varint,8,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// databroker versions of the change
	DbVersions []uint64 `protobuf:"varint,9,rep,packed,name=db_versions,json=dbVersions,proto3" json:"db_versions,omitempty"`
	// if true, show activity for the namespace and any child namespaces
	RecurseNamespace *bool `protobuf:"varint,11,opt,name=recurse_namespace,json=recurseNamespace,proto3,oneof" json:"recurse_namespace,omitempty"`
	// the entities are a list of entities to retrieve the activity log for
	Entities      []*ListActivityLogEntriesRequest_Entity     `protobuf:"bytes,10,rep,name=entities,proto3" json:"entities,omitempty"`
	Sort          *ListActivityLogEntriesRequest_Sort         `protobuf:"bytes,12,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	DateFilter    *ListActivityLogEntriesRequest_DateFilter   `protobuf:"bytes,13,opt,name=date_filter,json=dateFilter,proto3" json:"date_filter,omitempty"`
	StringFilter  *ListActivityLogEntriesRequest_StringFilter `protobuf:"bytes,14,opt,name=string_filter,json=stringFilter,proto3" json:"string_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivityLogEntriesRequest) Reset() {
	*x = ListActivityLogEntriesRequest{}
	mi := &file_activity_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivityLogEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityLogEntriesRequest) ProtoMessage() {}

func (x *ListActivityLogEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityLogEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListActivityLogEntriesRequest) Descriptor() ([]byte, []int) {
	return file_activity_log_proto_rawDescGZIP(), []int{3}
}

func (x *ListActivityLogEntriesRequest) GetActivityType() string {
	if x != nil && x.ActivityType != nil {
		return *x.ActivityType
	}
	return ""
}

func (x *ListActivityLogEntriesRequest) GetNamespaceId() string {
	if x != nil && x.NamespaceId != nil {
		return *x.NamespaceId
	}
	return ""
}

func (x *ListActivityLogEntriesRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *ListActivityLogEntriesRequest) GetEntityType() string {
	if x != nil && x.EntityType != nil {
		return *x.EntityType
	}
	return ""
}

func (x *ListActivityLogEntriesRequest) GetEntityId() string {
	if x != nil && x.EntityId != nil {
		return *x.EntityId
	}
	return ""
}

func (x *ListActivityLogEntriesRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *ListActivityLogEntriesRequest) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ListActivityLogEntriesRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListActivityLogEntriesRequest) GetDbVersions() []uint64 {
	if x != nil {
		return x.DbVersions
	}
	return nil
}

func (x *ListActivityLogEntriesRequest) GetRecurseNamespace() bool {
	if x != nil && x.RecurseNamespace != nil {
		return *x.RecurseNamespace
	}
	return false
}

func (x *ListActivityLogEntriesRequest) GetEntities() []*ListActivityLogEntriesRequest_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ListActivityLogEntriesRequest) GetSort() *ListActivityLogEntriesRequest_Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListActivityLogEntriesRequest) GetDateFilter() *ListActivityLogEntriesRequest_DateFilter {
	if x != nil {
		return x.DateFilter
	}
	return nil
}

func (x *ListActivityLogEntriesRequest) GetStringFilter() *ListActivityLogEntriesRequest_StringFilter {
	if x != nil {
		return x.StringFilter
	}
	return nil
}

// ListActivityLogEntriesResponse is a list of Activity Log entries found from a
// ListActivityLogEntriesRequest
type ListActivityLogEntriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Activity Log entries
	Entries       []*ActivityLogEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalCount    int64               `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivityLogEntriesResponse) Reset() {
	*x = ListActivityLogEntriesResponse{}
	mi := &file_activity_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivityLogEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityLogEntriesResponse) ProtoMessage() {}

func (x *ListActivityLogEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityLogEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListActivityLogEntriesResponse) Descriptor() ([]byte, []int) {
	return file_activity_log_proto_rawDescGZIP(), []int{4}
}

func (x *ListActivityLogEntriesResponse) GetEntries() []*ActivityLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListActivityLogEntriesResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ActivityLogEntry_DiffSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// number of lines added
	Added int64 `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	// number of lines removed
	Removed       int64 `protobuf:"varint,2,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityLogEntry_DiffSummary) Reset() {
	*x = ActivityLogEntry_DiffSummary{}
	mi := &file_activity_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityLogEntry_DiffSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityLogEntry_DiffSummary) ProtoMessage() {}

func (x *ActivityLogEntry_DiffSummary) ProtoReflect() protoreflect.Message {
	mi := &file_activity_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityLogEntry_DiffSummary.ProtoReflect.Descriptor instead.
func (*ActivityLogEntry_DiffSummary) Descriptor() ([]byte, []int) {
	return file_activity_log_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ActivityLogEntry_DiffSummary) GetAdded() int64 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *ActivityLogEntry_DiffSummary) GetRemoved() int64 {
	if x != nil {
		return x.Removed
	}
	return 0
}

// an entity is a single entity (route, policy, etc.)
type ListActivityLogEntriesRequest_Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivityLogEntriesRequest_Entity) Reset() {
	*x = ListActivityLogEntriesRequest_Entity{}
	mi := &file_activity_log_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivityLogEntriesRequest_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityLogEntriesRequest_Entity) ProtoMessage() {}

func (x *ListActivityLogEntriesRequest_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_activity_log_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityLogEntriesRequest_Entity.ProtoReflect.Descriptor instead.
func (*ListActivityLogEntriesRequest_Entity) Descriptor() ([]byte, []int) {
	return file_activity_log_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListActivityLogEntriesRequest_Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListActivityLogEntriesRequest_Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// used to sort the db query
type ListActivityLogEntriesRequest_Sort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `activity_type` | `created_at` | `namespace_name` | `user_name` |
	// `user_email` | `entity_type`
	Column string `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	// `ASC` | `DESC`
	Direction     string `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivityLogEntriesRequest_Sort) Reset() {
	*x = ListActivityLogEntriesRequest_Sort{}
	mi := &file_activity_log_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivityLogEntriesRequest_Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityLogEntriesRequest_Sort) ProtoMessage() {}

func (x *ListActivityLogEntriesRequest_Sort) ProtoReflect() protoreflect.Message {
	mi := &file_activity_log_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityLogEntriesRequest_Sort.ProtoReflect.Descriptor instead.
func (*ListActivityLogEntriesRequest_Sort) Descriptor() ([]byte, []int) {
	return file_activity_log_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ListActivityLogEntriesRequest_Sort) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *ListActivityLogEntriesRequest_Sort) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

// filter for dates
type ListActivityLogEntriesRequest_DateFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `=` | `!=` | `<` | `<=` | `>` | `>=`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivityLogEntriesRequest_DateFilter) Reset() {
	*x = ListActivityLogEntriesRequest_DateFilter{}
	mi := &file_activity_log_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivityLogEntriesRequest_DateFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityLogEntriesRequest_DateFilter) ProtoMessage() {}

func (x *ListActivityLogEntriesRequest_DateFilter) ProtoReflect() protoreflect.Message {
	mi := &file_activity_log_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityLogEntriesRequest_DateFilter.ProtoReflect.Descriptor instead.
func (*ListActivityLogEntriesRequest_DateFilter) Descriptor() ([]byte, []int) {
	return file_activity_log_proto_rawDescGZIP(), []int{3, 2}
}

func (x *ListActivityLogEntriesRequest_DateFilter) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ListActivityLogEntriesRequest_DateFilter) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

// filter for strings
type ListActivityLogEntriesRequest_StringFilter struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FieldName string                 `protobuf:"bytes,1,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	// `contains` | `equals` | `startsWith` | `endsWith`
	Operator      string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivityLogEntriesRequest_StringFilter) Reset() {
	*x = ListActivityLogEntriesRequest_StringFilter{}
	mi := &file_activity_log_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivityLogEntriesRequest_StringFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityLogEntriesRequest_StringFilter) ProtoMessage() {}

func (x *ListActivityLogEntriesRequest_StringFilter) ProtoReflect() protoreflect.Message {
	mi := &file_activity_log_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityLogEntriesRequest_StringFilter.ProtoReflect.Descriptor instead.
func (*ListActivityLogEntriesRequest_StringFilter) Descriptor() ([]byte, []int) {
	return file_activity_log_proto_rawDescGZIP(), []int{3, 3}
}

func (x *ListActivityLogEntriesRequest_StringFilter) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *ListActivityLogEntriesRequest_StringFilter) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ListActivityLogEntriesRequest_StringFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_activity_log_proto protoreflect.FileDescriptor

const file_activity_log_proto_rawDesc = "" +
	"\n" +
	"\x12activity_log.proto\x12\x12pomerium.dashboard\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\a\n" +
	"\x10ActivityLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x14 \x01(\tR\x04name\x12#\n" +
	"\ractivity_type\x18\x02 \x01(\tR\factivityType\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\"\n" +
	"\n" +
	"cluster_id\x18\x15 \x01(\tH\x00R\tclusterId\x88\x01\x01\x12!\n" +
	"\fnamespace_id\x18\x04 \x01(\tR\vnamespaceId\x12%\n" +
	"\x0enamespace_name\x18\x05 \x01(\tR\rnamespaceName\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\a \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"user_email\x18\b \x01(\tR\tuserEmail\x12\x1f\n" +
	"\ventity_type\x18\t \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\n" +
	" \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_data\x18\v \x01(\tR\n" +
	"entityData\x12S\n" +
	"\fdiff_summary\x18\f \x01(\v20.pomerium.dashboard.ActivityLogEntry.DiffSummaryR\vdiffSummary\x12\x1d\n" +
	"\n" +
	"db_version\x18\r \x01(\x04R\tdbVersion\x12\x1d\n" +
	"\n" +
	"session_id\x18\x0e \x01(\tR\tsessionId\x12,\n" +
	"\x12service_account_id\x18\x0f \x01(\tR\x10serviceAccountId\x12.\n" +
	"\x13impersonate_user_id\x18\x10 \x01(\tR\x11impersonateUserId\x122\n" +
	"\x15impersonate_user_name\x18\x11 \x01(\tR\x13impersonateUserName\x124\n" +
	"\x16impersonate_user_email\x18\x12 \x01(\tR\x14impersonateUserEmail\x126\n" +
	"\x17impersonate_user_groups\x18\x13 \x03(\tR\x15impersonateUserGroups\x1a=\n" +
	"\vDiffSummary\x12\x14\n" +
	"\x05added\x18\x01 \x01(\x03R\x05added\x12\x18\n" +
	"\aremoved\x18\x02 \x01(\x03R\aremovedB\r\n" +
	"\v_cluster_id\",\n" +
	"\x1aGetActivityLogEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xdb\x01\n" +
	"\x1bGetActivityLogEntryResponse\x12:\n" +
	"\x05entry\x18\x01 \x01(\v2$.pomerium.dashboard.ActivityLogEntryR\x05entry\x12/\n" +
	"\x11previous_entry_id\x18\x02 \x01(\tH\x00R\x0fpreviousEntryId\x88\x01\x01\x12'\n" +
	"\rnext_entry_id\x18\x03 \x01(\tH\x01R\vnextEntryId\x88\x01\x01B\x14\n" +
	"\x12_previous_entry_idB\x10\n" +
	"\x0e_next_entry_id\"\x99\t\n" +
	"\x1dListActivityLogEntriesRequest\x12(\n" +
	"\ractivity_type\x18\x01 \x01(\tH\x00R\factivityType\x88\x01\x01\x12&\n" +
	"\fnamespace_id\x18\x02 \x01(\tH\x01R\vnamespaceId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\tH\x02R\x06userId\x88\x01\x01\x12$\n" +
	"\ventity_type\x18\x04 \x01(\tH\x03R\n" +
	"entityType\x88\x01\x01\x12 \n" +
	"\tentity_id\x18\x05 \x01(\tH\x04R\bentityId\x88\x01\x01\x12\x19\n" +
	"\x05query\x18\x06 \x01(\tH\x05R\x05query\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\a \x01(\x03H\x06R\x06offset\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\b \x01(\x03H\aR\x05limit\x88\x01\x01\x12\x1f\n" +
	"\vdb_versions\x18\t \x03(\x04R\n" +
	"dbVersions\x120\n" +
	"\x11recurse_namespace\x18\v \x01(\bH\bR\x10recurseNamespace\x88\x01\x01\x12T\n" +
	"\bentities\x18\n" +
	" \x03(\v28.pomerium.dashboard.ListActivityLogEntriesRequest.EntityR\bentities\x12O\n" +
	"\x04sort\x18\f \x01(\v26.pomerium.dashboard.ListActivityLogEntriesRequest.SortH\tR\x04sort\x88\x01\x01\x12]\n" +
	"\vdate_filter\x18\r \x01(\v2<.pomerium.dashboard.ListActivityLogEntriesRequest.DateFilterR\n" +
	"dateFilter\x12c\n" +
	"\rstring_filter\x18\x0e \x01(\v2>.pomerium.dashboard.ListActivityLogEntriesRequest.StringFilterR\fstringFilter\x1a,\n" +
	"\x06Entity\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x1a<\n" +
	"\x04Sort\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x1aX\n" +
	"\n" +
	"DateFilter\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x1a^\n" +
	"\fStringFilter\x12\x1c\n" +
	"\tfieldName\x18\x01 \x01(\tR\tfieldName\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05valueB\x10\n" +
	"\x0e_activity_typeB\x0f\n" +
	"\r_namespace_idB\n" +
	"\n" +
	"\b_user_idB\x0e\n" +
	"\f_entity_typeB\f\n" +
	"\n" +
	"_entity_idB\b\n" +
	"\x06_queryB\t\n" +
	"\a_offsetB\b\n" +
	"\x06_limitB\x14\n" +
	"\x12_recurse_namespaceB\a\n" +
	"\x05_sort\"\x81\x01\n" +
	"\x1eListActivityLogEntriesResponse\x12>\n" +
	"\aentries\x18\x01 \x03(\v2$.pomerium.dashboard.ActivityLogEntryR\aentries\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount2\x8d\x02\n" +
	"\x12ActivityLogService\x12v\n" +
	"\x13GetActivityLogEntry\x12..pomerium.dashboard.GetActivityLogEntryRequest\x1a/.pomerium.dashboard.GetActivityLogEntryResponse\x12\x7f\n" +
	"\x16ListActivityLogEntries\x121.pomerium.dashboard.ListActivityLogEntriesRequest\x1a2.pomerium.dashboard.ListActivityLogEntriesResponseB-Z+github.com/pomerium/pomerium-console/pkg/pbb\x06proto3"

var (
	file_activity_log_proto_rawDescOnce sync.Once
	file_activity_log_proto_rawDescData []byte
)

func file_activity_log_proto_rawDescGZIP() []byte {
	file_activity_log_proto_rawDescOnce.Do(func() {
		file_activity_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_log_proto_rawDesc), len(file_activity_log_proto_rawDesc)))
	})
	return file_activity_log_proto_rawDescData
}

var file_activity_log_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_activity_log_proto_goTypes = []any{
	(*ActivityLogEntry)(nil),                           // 0: pomerium.dashboard.ActivityLogEntry
	(*GetActivityLogEntryRequest)(nil),                 // 1: pomerium.dashboard.GetActivityLogEntryRequest
	(*GetActivityLogEntryResponse)(nil),                // 2: pomerium.dashboard.GetActivityLogEntryResponse
	(*ListActivityLogEntriesRequest)(nil),              // 3: pomerium.dashboard.ListActivityLogEntriesRequest
	(*ListActivityLogEntriesResponse)(nil),             // 4: pomerium.dashboard.ListActivityLogEntriesResponse
	(*ActivityLogEntry_DiffSummary)(nil),               // 5: pomerium.dashboard.ActivityLogEntry.DiffSummary
	(*ListActivityLogEntriesRequest_Entity)(nil),       // 6: pomerium.dashboard.ListActivityLogEntriesRequest.Entity
	(*ListActivityLogEntriesRequest_Sort)(nil),         // 7: pomerium.dashboard.ListActivityLogEntriesRequest.Sort
	(*ListActivityLogEntriesRequest_DateFilter)(nil),   // 8: pomerium.dashboard.ListActivityLogEntriesRequest.DateFilter
	(*ListActivityLogEntriesRequest_StringFilter)(nil), // 9: pomerium.dashboard.ListActivityLogEntriesRequest.StringFilter
	(*timestamppb.Timestamp)(nil),                      // 10: google.protobuf.Timestamp
}
var file_activity_log_proto_depIdxs = []int32{
	10, // 0: pomerium.dashboard.ActivityLogEntry.created_at:type_name -> google.protobuf.Timestamp
	5,  // 1: pomerium.dashboard.ActivityLogEntry.diff_summary:type_name -> pomerium.dashboard.ActivityLogEntry.DiffSummary
	0,  // 2: pomerium.dashboard.GetActivityLogEntryResponse.entry:type_name -> pomerium.dashboard.ActivityLogEntry
	6,  // 3: pomerium.dashboard.ListActivityLogEntriesRequest.entities:type_name -> pomerium.dashboard.ListActivityLogEntriesRequest.Entity
	7,  // 4: pomerium.dashboard.ListActivityLogEntriesRequest.sort:type_name -> pomerium.dashboard.ListActivityLogEntriesRequest.Sort
	8,  // 5: pomerium.dashboard.ListActivityLogEntriesRequest.date_filter:type_name -> pomerium.dashboard.ListActivityLogEntriesRequest.DateFilter
	9,  // 6: pomerium.dashboard.ListActivityLogEntriesRequest.string_filter:type_name -> pomerium.dashboard.ListActivityLogEntriesRequest.StringFilter
	0,  // 7: pomerium.dashboard.ListActivityLogEntriesResponse.entries:type_name -> pomerium.dashboard.ActivityLogEntry
	10, // 8: pomerium.dashboard.ListActivityLogEntriesRequest.DateFilter.date:type_name -> google.protobuf.Timestamp
	1,  // 9: pomerium.dashboard.ActivityLogService.GetActivityLogEntry:input_type -> pomerium.dashboard.GetActivityLogEntryRequest
	3,  // 10: pomerium.dashboard.ActivityLogService.ListActivityLogEntries:input_type -> pomerium.dashboard.ListActivityLogEntriesRequest
	2,  // 11: pomerium.dashboard.ActivityLogService.GetActivityLogEntry:output_type -> pomerium.dashboard.GetActivityLogEntryResponse
	4,  // 12: pomerium.dashboard.ActivityLogService.ListActivityLogEntries:output_type -> pomerium.dashboard.ListActivityLogEntriesResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_activity_log_proto_init() }
func file_activity_log_proto_init() {
	if File_activity_log_proto != nil {
		return
	}
	file_activity_log_proto_msgTypes[0].OneofWrappers = []any{}
	file_activity_log_proto_msgTypes[2].OneofWrappers = []any{}
	file_activity_log_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_log_proto_rawDesc), len(file_activity_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_activity_log_proto_goTypes,
		DependencyIndexes: file_activity_log_proto_depIdxs,
		MessageInfos:      file_activity_log_proto_msgTypes,
	}.Build()
	File_activity_log_proto = out.File
	file_activity_log_proto_goTypes = nil
	file_activity_log_proto_depIdxs = nil
}
