// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: clusters.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cluster struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt                *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt               *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	DeletedAt                *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Name                     string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	DatabrokerServiceUrl     string                 `protobuf:"bytes,6,opt,name=databroker_service_url,json=databrokerServiceUrl,proto3" json:"databroker_service_url,omitempty"`
	SharedSecret             []byte                 `protobuf:"bytes,7,opt,name=shared_secret,json=sharedSecret,proto3" json:"shared_secret,omitempty"`
	InsecureSkipVerify       *bool                  `protobuf:"varint,8,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3,oneof" json:"insecure_skip_verify,omitempty"`
	OverrideCertificateName  *string                `protobuf:"bytes,9,opt,name=override_certificate_name,json=overrideCertificateName,proto3,oneof" json:"override_certificate_name,omitempty"`
	CertificateAuthority     []byte                 `protobuf:"bytes,10,opt,name=certificate_authority,json=certificateAuthority,proto3,oneof" json:"certificate_authority,omitempty"`
	CertificateAuthorityFile *string                `protobuf:"bytes,11,opt,name=certificate_authority_file,json=certificateAuthorityFile,proto3,oneof" json:"certificate_authority_file,omitempty"`
	OriginatorId             string                 `protobuf:"bytes,12,opt,name=originator_id,json=originatorId,proto3" json:"originator_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_clusters_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{0}
}

func (x *Cluster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cluster) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Cluster) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *Cluster) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetDatabrokerServiceUrl() string {
	if x != nil {
		return x.DatabrokerServiceUrl
	}
	return ""
}

func (x *Cluster) GetSharedSecret() []byte {
	if x != nil {
		return x.SharedSecret
	}
	return nil
}

func (x *Cluster) GetInsecureSkipVerify() bool {
	if x != nil && x.InsecureSkipVerify != nil {
		return *x.InsecureSkipVerify
	}
	return false
}

func (x *Cluster) GetOverrideCertificateName() string {
	if x != nil && x.OverrideCertificateName != nil {
		return *x.OverrideCertificateName
	}
	return ""
}

func (x *Cluster) GetCertificateAuthority() []byte {
	if x != nil {
		return x.CertificateAuthority
	}
	return nil
}

func (x *Cluster) GetCertificateAuthorityFile() string {
	if x != nil && x.CertificateAuthorityFile != nil {
		return *x.CertificateAuthorityFile
	}
	return ""
}

func (x *Cluster) GetOriginatorId() string {
	if x != nil {
		return x.OriginatorId
	}
	return ""
}

type AddClusterRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ParentNamespaceId string                 `protobuf:"bytes,1,opt,name=parent_namespace_id,json=parentNamespaceId,proto3" json:"parent_namespace_id,omitempty"`
	Cluster           *Cluster               `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddClusterRequest) Reset() {
	*x = AddClusterRequest{}
	mi := &file_clusters_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClusterRequest) ProtoMessage() {}

func (x *AddClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClusterRequest.ProtoReflect.Descriptor instead.
func (*AddClusterRequest) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{1}
}

func (x *AddClusterRequest) GetParentNamespaceId() string {
	if x != nil {
		return x.ParentNamespaceId
	}
	return ""
}

func (x *AddClusterRequest) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type AddClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Namespace     *Namespace             `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Settings      *Settings              `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClusterResponse) Reset() {
	*x = AddClusterResponse{}
	mi := &file_clusters_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClusterResponse) ProtoMessage() {}

func (x *AddClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClusterResponse.ProtoReflect.Descriptor instead.
func (*AddClusterResponse) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{2}
}

func (x *AddClusterResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *AddClusterResponse) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *AddClusterResponse) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type DeleteClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClusterRequest) Reset() {
	*x = DeleteClusterRequest{}
	mi := &file_clusters_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClusterRequest) ProtoMessage() {}

func (x *DeleteClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClusterRequest.ProtoReflect.Descriptor instead.
func (*DeleteClusterRequest) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteClusterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClusterResponse) Reset() {
	*x = DeleteClusterResponse{}
	mi := &file_clusters_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClusterResponse) ProtoMessage() {}

func (x *DeleteClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClusterResponse.ProtoReflect.Descriptor instead.
func (*DeleteClusterResponse) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{4}
}

type GetClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterRequest) Reset() {
	*x = GetClusterRequest{}
	mi := &file_clusters_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterRequest) ProtoMessage() {}

func (x *GetClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterRequest.ProtoReflect.Descriptor instead.
func (*GetClusterRequest) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{5}
}

func (x *GetClusterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Namespace     *Namespace             `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Settings      *Settings              `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterResponse) Reset() {
	*x = GetClusterResponse{}
	mi := &file_clusters_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterResponse) ProtoMessage() {}

func (x *GetClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterResponse.ProtoReflect.Descriptor instead.
func (*GetClusterResponse) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{6}
}

func (x *GetClusterResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *GetClusterResponse) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *GetClusterResponse) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ListClustersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersRequest) Reset() {
	*x = ListClustersRequest{}
	mi := &file_clusters_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersRequest) ProtoMessage() {}

func (x *ListClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersRequest.ProtoReflect.Descriptor instead.
func (*ListClustersRequest) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{7}
}

type ListClustersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*Cluster             `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersResponse) Reset() {
	*x = ListClustersResponse{}
	mi := &file_clusters_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersResponse) ProtoMessage() {}

func (x *ListClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersResponse.ProtoReflect.Descriptor instead.
func (*ListClustersResponse) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{8}
}

func (x *ListClustersResponse) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type UpdateClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterRequest) Reset() {
	*x = UpdateClusterRequest{}
	mi := &file_clusters_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterRequest) ProtoMessage() {}

func (x *UpdateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterRequest.ProtoReflect.Descriptor instead.
func (*UpdateClusterRequest) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateClusterRequest) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type UpdateClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *Cluster               `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Namespace     *Namespace             `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Settings      *Settings              `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterResponse) Reset() {
	*x = UpdateClusterResponse{}
	mi := &file_clusters_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterResponse) ProtoMessage() {}

func (x *UpdateClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusters_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterResponse.ProtoReflect.Descriptor instead.
func (*UpdateClusterResponse) Descriptor() ([]byte, []int) {
	return file_clusters_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateClusterResponse) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *UpdateClusterResponse) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *UpdateClusterResponse) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_clusters_proto protoreflect.FileDescriptor

const file_clusters_proto_rawDesc = "" +
	"\n" +
	"\x0eclusters.proto\x12\x12pomerium.dashboard\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10namespaces.proto\x1a\x0esettings.proto\"\xc5\x05\n" +
	"\aCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x124\n" +
	"\x16databroker_service_url\x18\x06 \x01(\tR\x14databrokerServiceUrl\x12#\n" +
	"\rshared_secret\x18\a \x01(\fR\fsharedSecret\x125\n" +
	"\x14insecure_skip_verify\x18\b \x01(\bH\x00R\x12insecureSkipVerify\x88\x01\x01\x12?\n" +
	"\x19override_certificate_name\x18\t \x01(\tH\x01R\x17overrideCertificateName\x88\x01\x01\x128\n" +
	"\x15certificate_authority\x18\n" +
	" \x01(\fH\x02R\x14certificateAuthority\x88\x01\x01\x12A\n" +
	"\x1acertificate_authority_file\x18\v \x01(\tH\x03R\x18certificateAuthorityFile\x88\x01\x01\x12#\n" +
	"\roriginator_id\x18\f \x01(\tR\foriginatorIdB\x17\n" +
	"\x15_insecure_skip_verifyB\x1c\n" +
	"\x1a_override_certificate_nameB\x18\n" +
	"\x16_certificate_authorityB\x1d\n" +
	"\x1b_certificate_authority_file\"z\n" +
	"\x11AddClusterRequest\x12.\n" +
	"\x13parent_namespace_id\x18\x01 \x01(\tR\x11parentNamespaceId\x125\n" +
	"\acluster\x18\x02 \x01(\v2\x1b.pomerium.dashboard.ClusterR\acluster\"\xc2\x01\n" +
	"\x12AddClusterResponse\x125\n" +
	"\acluster\x18\x01 \x01(\v2\x1b.pomerium.dashboard.ClusterR\acluster\x12;\n" +
	"\tnamespace\x18\x02 \x01(\v2\x1d.pomerium.dashboard.NamespaceR\tnamespace\x128\n" +
	"\bsettings\x18\x03 \x01(\v2\x1c.pomerium.dashboard.SettingsR\bsettings\"&\n" +
	"\x14DeleteClusterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteClusterResponse\"#\n" +
	"\x11GetClusterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc2\x01\n" +
	"\x12GetClusterResponse\x125\n" +
	"\acluster\x18\x01 \x01(\v2\x1b.pomerium.dashboard.ClusterR\acluster\x12;\n" +
	"\tnamespace\x18\x02 \x01(\v2\x1d.pomerium.dashboard.NamespaceR\tnamespace\x128\n" +
	"\bsettings\x18\x03 \x01(\v2\x1c.pomerium.dashboard.SettingsR\bsettings\"\x15\n" +
	"\x13ListClustersRequest\"O\n" +
	"\x14ListClustersResponse\x127\n" +
	"\bclusters\x18\x01 \x03(\v2\x1b.pomerium.dashboard.ClusterR\bclusters\"M\n" +
	"\x14UpdateClusterRequest\x125\n" +
	"\acluster\x18\x01 \x01(\v2\x1b.pomerium.dashboard.ClusterR\acluster\"\xc5\x01\n" +
	"\x15UpdateClusterResponse\x125\n" +
	"\acluster\x18\x01 \x01(\v2\x1b.pomerium.dashboard.ClusterR\acluster\x12;\n" +
	"\tnamespace\x18\x02 \x01(\v2\x1d.pomerium.dashboard.NamespaceR\tnamespace\x128\n" +
	"\bsettings\x18\x03 \x01(\v2\x1c.pomerium.dashboard.SettingsR\bsettings2\xfa\x03\n" +
	"\x0fClustersService\x12[\n" +
	"\n" +
	"AddCluster\x12%.pomerium.dashboard.AddClusterRequest\x1a&.pomerium.dashboard.AddClusterResponse\x12d\n" +
	"\rDeleteCluster\x12(.pomerium.dashboard.DeleteClusterRequest\x1a).pomerium.dashboard.DeleteClusterResponse\x12[\n" +
	"\n" +
	"GetCluster\x12%.pomerium.dashboard.GetClusterRequest\x1a&.pomerium.dashboard.GetClusterResponse\x12a\n" +
	"\fListClusters\x12'.pomerium.dashboard.ListClustersRequest\x1a(.pomerium.dashboard.ListClustersResponse\x12d\n" +
	"\rUpdateCluster\x12(.pomerium.dashboard.UpdateClusterRequest\x1a).pomerium.dashboard.UpdateClusterResponseB-Z+github.com/pomerium/pomerium-console/pkg/pbb\x06proto3"

var (
	file_clusters_proto_rawDescOnce sync.Once
	file_clusters_proto_rawDescData []byte
)

func file_clusters_proto_rawDescGZIP() []byte {
	file_clusters_proto_rawDescOnce.Do(func() {
		file_clusters_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusters_proto_rawDesc), len(file_clusters_proto_rawDesc)))
	})
	return file_clusters_proto_rawDescData
}

var file_clusters_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_clusters_proto_goTypes = []any{
	(*Cluster)(nil),               // 0: pomerium.dashboard.Cluster
	(*AddClusterRequest)(nil),     // 1: pomerium.dashboard.AddClusterRequest
	(*AddClusterResponse)(nil),    // 2: pomerium.dashboard.AddClusterResponse
	(*DeleteClusterRequest)(nil),  // 3: pomerium.dashboard.DeleteClusterRequest
	(*DeleteClusterResponse)(nil), // 4: pomerium.dashboard.DeleteClusterResponse
	(*GetClusterRequest)(nil),     // 5: pomerium.dashboard.GetClusterRequest
	(*GetClusterResponse)(nil),    // 6: pomerium.dashboard.GetClusterResponse
	(*ListClustersRequest)(nil),   // 7: pomerium.dashboard.ListClustersRequest
	(*ListClustersResponse)(nil),  // 8: pomerium.dashboard.ListClustersResponse
	(*UpdateClusterRequest)(nil),  // 9: pomerium.dashboard.UpdateClusterRequest
	(*UpdateClusterResponse)(nil), // 10: pomerium.dashboard.UpdateClusterResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*Namespace)(nil),             // 12: pomerium.dashboard.Namespace
	(*Settings)(nil),              // 13: pomerium.dashboard.Settings
}
var file_clusters_proto_depIdxs = []int32{
	11, // 0: pomerium.dashboard.Cluster.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: pomerium.dashboard.Cluster.modified_at:type_name -> google.protobuf.Timestamp
	11, // 2: pomerium.dashboard.Cluster.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: pomerium.dashboard.AddClusterRequest.cluster:type_name -> pomerium.dashboard.Cluster
	0,  // 4: pomerium.dashboard.AddClusterResponse.cluster:type_name -> pomerium.dashboard.Cluster
	12, // 5: pomerium.dashboard.AddClusterResponse.namespace:type_name -> pomerium.dashboard.Namespace
	13, // 6: pomerium.dashboard.AddClusterResponse.settings:type_name -> pomerium.dashboard.Settings
	0,  // 7: pomerium.dashboard.GetClusterResponse.cluster:type_name -> pomerium.dashboard.Cluster
	12, // 8: pomerium.dashboard.GetClusterResponse.namespace:type_name -> pomerium.dashboard.Namespace
	13, // 9: pomerium.dashboard.GetClusterResponse.settings:type_name -> pomerium.dashboard.Settings
	0,  // 10: pomerium.dashboard.ListClustersResponse.clusters:type_name -> pomerium.dashboard.Cluster
	0,  // 11: pomerium.dashboard.UpdateClusterRequest.cluster:type_name -> pomerium.dashboard.Cluster
	0,  // 12: pomerium.dashboard.UpdateClusterResponse.cluster:type_name -> pomerium.dashboard.Cluster
	12, // 13: pomerium.dashboard.UpdateClusterResponse.namespace:type_name -> pomerium.dashboard.Namespace
	13, // 14: pomerium.dashboard.UpdateClusterResponse.settings:type_name -> pomerium.dashboard.Settings
	1,  // 15: pomerium.dashboard.ClustersService.AddCluster:input_type -> pomerium.dashboard.AddClusterRequest
	3,  // 16: pomerium.dashboard.ClustersService.DeleteCluster:input_type -> pomerium.dashboard.DeleteClusterRequest
	5,  // 17: pomerium.dashboard.ClustersService.GetCluster:input_type -> pomerium.dashboard.GetClusterRequest
	7,  // 18: pomerium.dashboard.ClustersService.ListClusters:input_type -> pomerium.dashboard.ListClustersRequest
	9,  // 19: pomerium.dashboard.ClustersService.UpdateCluster:input_type -> pomerium.dashboard.UpdateClusterRequest
	2,  // 20: pomerium.dashboard.ClustersService.AddCluster:output_type -> pomerium.dashboard.AddClusterResponse
	4,  // 21: pomerium.dashboard.ClustersService.DeleteCluster:output_type -> pomerium.dashboard.DeleteClusterResponse
	6,  // 22: pomerium.dashboard.ClustersService.GetCluster:output_type -> pomerium.dashboard.GetClusterResponse
	8,  // 23: pomerium.dashboard.ClustersService.ListClusters:output_type -> pomerium.dashboard.ListClustersResponse
	10, // 24: pomerium.dashboard.ClustersService.UpdateCluster:output_type -> pomerium.dashboard.UpdateClusterResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_clusters_proto_init() }
func file_clusters_proto_init() {
	if File_clusters_proto != nil {
		return
	}
	file_namespaces_proto_init()
	file_settings_proto_init()
	file_clusters_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusters_proto_rawDesc), len(file_clusters_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clusters_proto_goTypes,
		DependencyIndexes: file_clusters_proto_depIdxs,
		MessageInfos:      file_clusters_proto_msgTypes,
	}.Build()
	File_clusters_proto = out.File
	file_clusters_proto_goTypes = nil
	file_clusters_proto_depIdxs = nil
}
