// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: recording_data.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecordingQuerierService_CreateDatasource_FullMethodName            = "/recording.RecordingQuerierService/CreateDatasource"
	RecordingQuerierService_GetDatasource_FullMethodName               = "/recording.RecordingQuerierService/GetDatasource"
	RecordingQuerierService_DeleteDatasource_FullMethodName            = "/recording.RecordingQuerierService/DeleteDatasource"
	RecordingQuerierService_ListDatasources_FullMethodName             = "/recording.RecordingQuerierService/ListDatasources"
	RecordingQuerierService_ListSessionRecording_FullMethodName        = "/recording.RecordingQuerierService/ListSessionRecording"
	RecordingQuerierService_GetSessionRecordingMetadata_FullMethodName = "/recording.RecordingQuerierService/GetSessionRecordingMetadata"
	RecordingQuerierService_GetContents_FullMethodName                 = "/recording.RecordingQuerierService/GetContents"
)

// RecordingQuerierServiceClient is the client API for RecordingQuerierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordingQuerierServiceClient interface {
	CreateDatasource(ctx context.Context, in *CreateDatasourceRequest, opts ...grpc.CallOption) (*CreateDatasourceResponse, error)
	GetDatasource(ctx context.Context, in *GetDatasourceRequest, opts ...grpc.CallOption) (*GetDatasourceResponse, error)
	DeleteDatasource(ctx context.Context, in *DeleteDatasourceRequest, opts ...grpc.CallOption) (*DeleteDatasourceResponse, error)
	ListDatasources(ctx context.Context, in *ListDatasourceRequest, opts ...grpc.CallOption) (*ListDatasourceResponse, error)
	ListSessionRecording(ctx context.Context, in *ListSessionRecordingRequest, opts ...grpc.CallOption) (*ListSessionRecordingResponse, error)
	GetSessionRecordingMetadata(ctx context.Context, in *GetSessionRecordingMetadataRequest, opts ...grpc.CallOption) (*GetSessionRecordingMetadataResponse, error)
	GetContents(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error)
}

type recordingQuerierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordingQuerierServiceClient(cc grpc.ClientConnInterface) RecordingQuerierServiceClient {
	return &recordingQuerierServiceClient{cc}
}

func (c *recordingQuerierServiceClient) CreateDatasource(ctx context.Context, in *CreateDatasourceRequest, opts ...grpc.CallOption) (*CreateDatasourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDatasourceResponse)
	err := c.cc.Invoke(ctx, RecordingQuerierService_CreateDatasource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordingQuerierServiceClient) GetDatasource(ctx context.Context, in *GetDatasourceRequest, opts ...grpc.CallOption) (*GetDatasourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDatasourceResponse)
	err := c.cc.Invoke(ctx, RecordingQuerierService_GetDatasource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordingQuerierServiceClient) DeleteDatasource(ctx context.Context, in *DeleteDatasourceRequest, opts ...grpc.CallOption) (*DeleteDatasourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDatasourceResponse)
	err := c.cc.Invoke(ctx, RecordingQuerierService_DeleteDatasource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordingQuerierServiceClient) ListDatasources(ctx context.Context, in *ListDatasourceRequest, opts ...grpc.CallOption) (*ListDatasourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatasourceResponse)
	err := c.cc.Invoke(ctx, RecordingQuerierService_ListDatasources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordingQuerierServiceClient) ListSessionRecording(ctx context.Context, in *ListSessionRecordingRequest, opts ...grpc.CallOption) (*ListSessionRecordingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionRecordingResponse)
	err := c.cc.Invoke(ctx, RecordingQuerierService_ListSessionRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordingQuerierServiceClient) GetSessionRecordingMetadata(ctx context.Context, in *GetSessionRecordingMetadataRequest, opts ...grpc.CallOption) (*GetSessionRecordingMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionRecordingMetadataResponse)
	err := c.cc.Invoke(ctx, RecordingQuerierService_GetSessionRecordingMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordingQuerierServiceClient) GetContents(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentResponse)
	err := c.cc.Invoke(ctx, RecordingQuerierService_GetContents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordingQuerierServiceServer is the server API for RecordingQuerierService service.
// All implementations should embed UnimplementedRecordingQuerierServiceServer
// for forward compatibility.
type RecordingQuerierServiceServer interface {
	CreateDatasource(context.Context, *CreateDatasourceRequest) (*CreateDatasourceResponse, error)
	GetDatasource(context.Context, *GetDatasourceRequest) (*GetDatasourceResponse, error)
	DeleteDatasource(context.Context, *DeleteDatasourceRequest) (*DeleteDatasourceResponse, error)
	ListDatasources(context.Context, *ListDatasourceRequest) (*ListDatasourceResponse, error)
	ListSessionRecording(context.Context, *ListSessionRecordingRequest) (*ListSessionRecordingResponse, error)
	GetSessionRecordingMetadata(context.Context, *GetSessionRecordingMetadataRequest) (*GetSessionRecordingMetadataResponse, error)
	GetContents(context.Context, *GetContentRequest) (*GetContentResponse, error)
}

// UnimplementedRecordingQuerierServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordingQuerierServiceServer struct{}

func (UnimplementedRecordingQuerierServiceServer) CreateDatasource(context.Context, *CreateDatasourceRequest) (*CreateDatasourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDatasource not implemented")
}
func (UnimplementedRecordingQuerierServiceServer) GetDatasource(context.Context, *GetDatasourceRequest) (*GetDatasourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDatasource not implemented")
}
func (UnimplementedRecordingQuerierServiceServer) DeleteDatasource(context.Context, *DeleteDatasourceRequest) (*DeleteDatasourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDatasource not implemented")
}
func (UnimplementedRecordingQuerierServiceServer) ListDatasources(context.Context, *ListDatasourceRequest) (*ListDatasourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatasources not implemented")
}
func (UnimplementedRecordingQuerierServiceServer) ListSessionRecording(context.Context, *ListSessionRecordingRequest) (*ListSessionRecordingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessionRecording not implemented")
}
func (UnimplementedRecordingQuerierServiceServer) GetSessionRecordingMetadata(context.Context, *GetSessionRecordingMetadataRequest) (*GetSessionRecordingMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionRecordingMetadata not implemented")
}
func (UnimplementedRecordingQuerierServiceServer) GetContents(context.Context, *GetContentRequest) (*GetContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContents not implemented")
}
func (UnimplementedRecordingQuerierServiceServer) testEmbeddedByValue() {}

// UnsafeRecordingQuerierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordingQuerierServiceServer will
// result in compilation errors.
type UnsafeRecordingQuerierServiceServer interface {
	mustEmbedUnimplementedRecordingQuerierServiceServer()
}

func RegisterRecordingQuerierServiceServer(s grpc.ServiceRegistrar, srv RecordingQuerierServiceServer) {
	// If the following call panics, it indicates UnimplementedRecordingQuerierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordingQuerierService_ServiceDesc, srv)
}

func _RecordingQuerierService_CreateDatasource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatasourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingQuerierServiceServer).CreateDatasource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordingQuerierService_CreateDatasource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingQuerierServiceServer).CreateDatasource(ctx, req.(*CreateDatasourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordingQuerierService_GetDatasource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatasourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingQuerierServiceServer).GetDatasource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordingQuerierService_GetDatasource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingQuerierServiceServer).GetDatasource(ctx, req.(*GetDatasourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordingQuerierService_DeleteDatasource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatasourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingQuerierServiceServer).DeleteDatasource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordingQuerierService_DeleteDatasource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingQuerierServiceServer).DeleteDatasource(ctx, req.(*DeleteDatasourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordingQuerierService_ListDatasources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatasourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingQuerierServiceServer).ListDatasources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordingQuerierService_ListDatasources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingQuerierServiceServer).ListDatasources(ctx, req.(*ListDatasourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordingQuerierService_ListSessionRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingQuerierServiceServer).ListSessionRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordingQuerierService_ListSessionRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingQuerierServiceServer).ListSessionRecording(ctx, req.(*ListSessionRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordingQuerierService_GetSessionRecordingMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRecordingMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingQuerierServiceServer).GetSessionRecordingMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordingQuerierService_GetSessionRecordingMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingQuerierServiceServer).GetSessionRecordingMetadata(ctx, req.(*GetSessionRecordingMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordingQuerierService_GetContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingQuerierServiceServer).GetContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordingQuerierService_GetContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingQuerierServiceServer).GetContents(ctx, req.(*GetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordingQuerierService_ServiceDesc is the grpc.ServiceDesc for RecordingQuerierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordingQuerierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recording.RecordingQuerierService",
	HandlerType: (*RecordingQuerierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDatasource",
			Handler:    _RecordingQuerierService_CreateDatasource_Handler,
		},
		{
			MethodName: "GetDatasource",
			Handler:    _RecordingQuerierService_GetDatasource_Handler,
		},
		{
			MethodName: "DeleteDatasource",
			Handler:    _RecordingQuerierService_DeleteDatasource_Handler,
		},
		{
			MethodName: "ListDatasources",
			Handler:    _RecordingQuerierService_ListDatasources_Handler,
		},
		{
			MethodName: "ListSessionRecording",
			Handler:    _RecordingQuerierService_ListSessionRecording_Handler,
		},
		{
			MethodName: "GetSessionRecordingMetadata",
			Handler:    _RecordingQuerierService_GetSessionRecordingMetadata_Handler,
		},
		{
			MethodName: "GetContents",
			Handler:    _RecordingQuerierService_GetContents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recording_data.proto",
}
