// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: settings.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CodecType int32

const (
	CodecType_CODEC_TYPE_UNKNOWN CodecType = 0
	CodecType_CODEC_TYPE_AUTO    CodecType = 1
	CodecType_CODEC_TYPE_HTTP1   CodecType = 2
	CodecType_CODEC_TYPE_HTTP2   CodecType = 3
	CodecType_CODEC_TYPE_HTTP3   CodecType = 4
)

// Enum value maps for CodecType.
var (
	CodecType_name = map[int32]string{
		0: "CODEC_TYPE_UNKNOWN",
		1: "CODEC_TYPE_AUTO",
		2: "CODEC_TYPE_HTTP1",
		3: "CODEC_TYPE_HTTP2",
		4: "CODEC_TYPE_HTTP3",
	}
	CodecType_value = map[string]int32{
		"CODEC_TYPE_UNKNOWN": 0,
		"CODEC_TYPE_AUTO":    1,
		"CODEC_TYPE_HTTP1":   2,
		"CODEC_TYPE_HTTP2":   3,
		"CODEC_TYPE_HTTP3":   4,
	}
)

func (x CodecType) Enum() *CodecType {
	p := new(CodecType)
	*p = x
	return p
}

func (x CodecType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CodecType) Descriptor() protoreflect.EnumDescriptor {
	return file_settings_proto_enumTypes[0].Descriptor()
}

func (CodecType) Type() protoreflect.EnumType {
	return &file_settings_proto_enumTypes[0]
}

func (x CodecType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CodecType.Descriptor instead.
func (CodecType) EnumDescriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{0}
}

type ConsoleSettings struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EnableFeedbackWidget bool                   `protobuf:"varint,1,opt,name=enable_feedback_widget,json=enableFeedbackWidget,proto3" json:"enable_feedback_widget,omitempty"`
	UseChangesets        bool                   `protobuf:"varint,2,opt,name=use_changesets,json=useChangesets,proto3" json:"use_changesets,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConsoleSettings) Reset() {
	*x = ConsoleSettings{}
	mi := &file_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleSettings) ProtoMessage() {}

func (x *ConsoleSettings) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleSettings.ProtoReflect.Descriptor instead.
func (*ConsoleSettings) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{0}
}

func (x *ConsoleSettings) GetEnableFeedbackWidget() bool {
	if x != nil {
		return x.EnableFeedbackWidget
	}
	return false
}

func (x *ConsoleSettings) GetUseChangesets() bool {
	if x != nil {
		return x.UseChangesets
	}
	return false
}

// Settings defines the global pomerium settings
// Next id: 122.
type Settings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,107,opt,name=id,proto3" json:"id,omitempty"`
	ClusterId      *string                `protobuf:"bytes,108,opt,name=cluster_id,json=clusterId,proto3,oneof" json:"cluster_id,omitempty"`
	ModifiedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	InstallationId *string                `protobuf:"bytes,68,opt,name=installation_id,json=installationId,proto3,oneof" json:"installation_id,omitempty"`
	LogLevel       *string                `protobuf:"bytes,3,opt,name=log_level,json=logLevel,proto3,oneof" json:"log_level,omitempty"`
	ProxyLogLevel  *string                `protobuf:"bytes,4,opt,name=proxy_log_level,json=proxyLogLevel,proto3,oneof" json:"proxy_log_level,omitempty"`
	SharedSecret   *string                `protobuf:"bytes,5,opt,name=shared_secret,json=sharedSecret,proto3,oneof" json:"shared_secret,omitempty"`
	Services       *string                `protobuf:"bytes,6,opt,name=services,proto3,oneof" json:"services,omitempty"`
	Address        *string                `protobuf:"bytes,7,opt,name=address,proto3,oneof" json:"address,omitempty"`
	InsecureServer *bool                  `protobuf:"varint,8,opt,name=insecure_server,json=insecureServer,proto3,oneof" json:"insecure_server,omitempty"`
	// dns options
	DnsFailureRefreshRate                             *durationpb.Duration      `protobuf:"bytes,120,opt,name=dns_failure_refresh_rate,json=dnsFailureRefreshRate,proto3,oneof" json:"dns_failure_refresh_rate,omitempty"`
	DnsLookupFamily                                   *string                   `protobuf:"bytes,60,opt,name=dns_lookup_family,json=dnsLookupFamily,proto3,oneof" json:"dns_lookup_family,omitempty"`
	DnsQueryTimeout                                   *durationpb.Duration      `protobuf:"bytes,119,opt,name=dns_query_timeout,json=dnsQueryTimeout,proto3,oneof" json:"dns_query_timeout,omitempty"`
	DnsQueryTries                                     *uint32                   `protobuf:"varint,118,opt,name=dns_query_tries,json=dnsQueryTries,proto3,oneof" json:"dns_query_tries,omitempty"`
	DnsRefreshRate                                    *durationpb.Duration      `protobuf:"bytes,121,opt,name=dns_refresh_rate,json=dnsRefreshRate,proto3,oneof" json:"dns_refresh_rate,omitempty"`
	DnsUdpMaxQueries                                  *uint32                   `protobuf:"varint,116,opt,name=dns_udp_max_queries,json=dnsUdpMaxQueries,proto3,oneof" json:"dns_udp_max_queries,omitempty"`
	DnsUseTcp                                         *bool                     `protobuf:"varint,117,opt,name=dns_use_tcp,json=dnsUseTcp,proto3,oneof" json:"dns_use_tcp,omitempty"`
	Certificates                                      []*Settings_Certificate   `protobuf:"bytes,9,rep,name=certificates,proto3" json:"certificates,omitempty"`
	HttpRedirectAddr                                  *string                   `protobuf:"bytes,10,opt,name=http_redirect_addr,json=httpRedirectAddr,proto3,oneof" json:"http_redirect_addr,omitempty"`
	TimeoutRead                                       *durationpb.Duration      `protobuf:"bytes,11,opt,name=timeout_read,json=timeoutRead,proto3,oneof" json:"timeout_read,omitempty"`
	TimeoutWrite                                      *durationpb.Duration      `protobuf:"bytes,12,opt,name=timeout_write,json=timeoutWrite,proto3,oneof" json:"timeout_write,omitempty"`
	TimeoutIdle                                       *durationpb.Duration      `protobuf:"bytes,13,opt,name=timeout_idle,json=timeoutIdle,proto3,oneof" json:"timeout_idle,omitempty"`
	AuthenticateServiceUrl                            *string                   `protobuf:"bytes,14,opt,name=authenticate_service_url,json=authenticateServiceUrl,proto3,oneof" json:"authenticate_service_url,omitempty"`
	CookieName                                        *string                   `protobuf:"bytes,16,opt,name=cookie_name,json=cookieName,proto3,oneof" json:"cookie_name,omitempty"`
	CookieSecret                                      *string                   `protobuf:"bytes,17,opt,name=cookie_secret,json=cookieSecret,proto3,oneof" json:"cookie_secret,omitempty"`
	CookieDomain                                      *string                   `protobuf:"bytes,18,opt,name=cookie_domain,json=cookieDomain,proto3,oneof" json:"cookie_domain,omitempty"`
	CookieSecure                                      *bool                     `protobuf:"varint,19,opt,name=cookie_secure,json=cookieSecure,proto3,oneof" json:"cookie_secure,omitempty"`
	CookieHttpOnly                                    *bool                     `protobuf:"varint,20,opt,name=cookie_http_only,json=cookieHttpOnly,proto3,oneof" json:"cookie_http_only,omitempty"`
	CookieSameSite                                    *string                   `protobuf:"bytes,80,opt,name=cookie_same_site,json=cookieSameSite,proto3,oneof" json:"cookie_same_site,omitempty"`
	CookieExpire                                      *durationpb.Duration      `protobuf:"bytes,21,opt,name=cookie_expire,json=cookieExpire,proto3,oneof" json:"cookie_expire,omitempty"`
	IdpClientId                                       *string                   `protobuf:"bytes,22,opt,name=idp_client_id,json=idpClientId,proto3,oneof" json:"idp_client_id,omitempty"`
	IdpClientSecret                                   *string                   `protobuf:"bytes,23,opt,name=idp_client_secret,json=idpClientSecret,proto3,oneof" json:"idp_client_secret,omitempty"`
	IdpProvider                                       *string                   `protobuf:"bytes,24,opt,name=idp_provider,json=idpProvider,proto3,oneof" json:"idp_provider,omitempty"`
	IdpProviderUrl                                    *string                   `protobuf:"bytes,25,opt,name=idp_provider_url,json=idpProviderUrl,proto3,oneof" json:"idp_provider_url,omitempty"`
	Scopes                                            []string                  `protobuf:"bytes,26,rep,name=scopes,proto3" json:"scopes,omitempty"`
	IdpServiceAccount                                 *string                   `protobuf:"bytes,27,opt,name=idp_service_account,json=idpServiceAccount,proto3,oneof" json:"idp_service_account,omitempty"`
	IdpRefreshDirectoryTimeout                        *durationpb.Duration      `protobuf:"bytes,28,opt,name=idp_refresh_directory_timeout,json=idpRefreshDirectoryTimeout,proto3,oneof" json:"idp_refresh_directory_timeout,omitempty"`
	IdpRefreshDirectoryInterval                       *durationpb.Duration      `protobuf:"bytes,29,opt,name=idp_refresh_directory_interval,json=idpRefreshDirectoryInterval,proto3,oneof" json:"idp_refresh_directory_interval,omitempty"`
	RequestParams                                     map[string]string         `protobuf:"bytes,30,rep,name=request_params,json=requestParams,proto3" json:"request_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AuthorizeServiceUrl                               *string                   `protobuf:"bytes,32,opt,name=authorize_service_url,json=authorizeServiceUrl,proto3,oneof" json:"authorize_service_url,omitempty"`
	CertificateAuthority                              *string                   `protobuf:"bytes,34,opt,name=certificate_authority,json=certificateAuthority,proto3,oneof" json:"certificate_authority,omitempty"`
	CertificateAuthorityFile                          *string                   `protobuf:"bytes,35,opt,name=certificate_authority_file,json=certificateAuthorityFile,proto3,oneof" json:"certificate_authority_file,omitempty"`
	CertificateAuthorityKeyPairId                     *string                   `protobuf:"bytes,64,opt,name=certificate_authority_key_pair_id,json=certificateAuthorityKeyPairId,proto3,oneof" json:"certificate_authority_key_pair_id,omitempty"`
	SetResponseHeaders                                map[string]string         `protobuf:"bytes,67,rep,name=set_response_headers,json=setResponseHeaders,proto3" json:"set_response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	JwtClaimsHeaders                                  map[string]string         `protobuf:"bytes,66,rep,name=jwt_claims_headers,json=jwtClaimsHeaders,proto3" json:"jwt_claims_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	JwtGroupsFilter                                   *JwtGroupsFilter          `protobuf:"bytes,87,opt,name=jwt_groups_filter,json=jwtGroupsFilter,proto3" json:"jwt_groups_filter,omitempty"`
	JwtIssuerFormat                                   *IssuerFormat             `protobuf:"varint,106,opt,name=jwt_issuer_format,json=jwtIssuerFormat,proto3,enum=pomerium.dashboard.IssuerFormat,oneof" json:"jwt_issuer_format,omitempty"`
	DefaultUpstreamTimeout                            *durationpb.Duration      `protobuf:"bytes,39,opt,name=default_upstream_timeout,json=defaultUpstreamTimeout,proto3,oneof" json:"default_upstream_timeout,omitempty"`
	MetricsAddress                                    *string                   `protobuf:"bytes,40,opt,name=metrics_address,json=metricsAddress,proto3,oneof" json:"metrics_address,omitempty"`
	OtelTracesExporter                                *string                   `protobuf:"bytes,88,opt,name=otel_traces_exporter,json=otelTracesExporter,proto3,oneof" json:"otel_traces_exporter,omitempty"`
	OtelTracesSamplerArg                              *float64                  `protobuf:"fixed64,89,opt,name=otel_traces_sampler_arg,json=otelTracesSamplerArg,proto3,oneof" json:"otel_traces_sampler_arg,omitempty"`
	OtelResourceAttributes                            []string                  `protobuf:"bytes,90,rep,name=otel_resource_attributes,json=otelResourceAttributes,proto3" json:"otel_resource_attributes,omitempty"`
	OtelLogLevel                                      *string                   `protobuf:"bytes,91,opt,name=otel_log_level,json=otelLogLevel,proto3,oneof" json:"otel_log_level,omitempty"`
	OtelAttributeValueLengthLimit                     *int32                    `protobuf:"varint,92,opt,name=otel_attribute_value_length_limit,json=otelAttributeValueLengthLimit,proto3,oneof" json:"otel_attribute_value_length_limit,omitempty"`
	OtelExporterOtlpEndpoint                          *string                   `protobuf:"bytes,93,opt,name=otel_exporter_otlp_endpoint,json=otelExporterOtlpEndpoint,proto3,oneof" json:"otel_exporter_otlp_endpoint,omitempty"`
	OtelExporterOtlpTracesEndpoint                    *string                   `protobuf:"bytes,94,opt,name=otel_exporter_otlp_traces_endpoint,json=otelExporterOtlpTracesEndpoint,proto3,oneof" json:"otel_exporter_otlp_traces_endpoint,omitempty"`
	OtelExporterOtlpProtocol                          *string                   `protobuf:"bytes,95,opt,name=otel_exporter_otlp_protocol,json=otelExporterOtlpProtocol,proto3,oneof" json:"otel_exporter_otlp_protocol,omitempty"`
	OtelExporterOtlpTracesProtocol                    *string                   `protobuf:"bytes,96,opt,name=otel_exporter_otlp_traces_protocol,json=otelExporterOtlpTracesProtocol,proto3,oneof" json:"otel_exporter_otlp_traces_protocol,omitempty"`
	OtelExporterOtlpHeaders                           []string                  `protobuf:"bytes,97,rep,name=otel_exporter_otlp_headers,json=otelExporterOtlpHeaders,proto3" json:"otel_exporter_otlp_headers,omitempty"`
	OtelExporterOtlpTracesHeaders                     []string                  `protobuf:"bytes,98,rep,name=otel_exporter_otlp_traces_headers,json=otelExporterOtlpTracesHeaders,proto3" json:"otel_exporter_otlp_traces_headers,omitempty"`
	OtelExporterOtlpTimeout                           *durationpb.Duration      `protobuf:"bytes,99,opt,name=otel_exporter_otlp_timeout,json=otelExporterOtlpTimeout,proto3,oneof" json:"otel_exporter_otlp_timeout,omitempty"`
	OtelExporterOtlpTracesTimeout                     *durationpb.Duration      `protobuf:"bytes,100,opt,name=otel_exporter_otlp_traces_timeout,json=otelExporterOtlpTracesTimeout,proto3,oneof" json:"otel_exporter_otlp_traces_timeout,omitempty"`
	OtelBspScheduleDelay                              *durationpb.Duration      `protobuf:"bytes,101,opt,name=otel_bsp_schedule_delay,json=otelBspScheduleDelay,proto3,oneof" json:"otel_bsp_schedule_delay,omitempty"`
	OtelBspMaxExportBatchSize                         *int32                    `protobuf:"varint,102,opt,name=otel_bsp_max_export_batch_size,json=otelBspMaxExportBatchSize,proto3,oneof" json:"otel_bsp_max_export_batch_size,omitempty"`
	GrpcAddress                                       *string                   `protobuf:"bytes,46,opt,name=grpc_address,json=grpcAddress,proto3,oneof" json:"grpc_address,omitempty"`
	GrpcInsecure                                      *bool                     `protobuf:"varint,47,opt,name=grpc_insecure,json=grpcInsecure,proto3,oneof" json:"grpc_insecure,omitempty"`
	CacheServiceUrl                                   *string                   `protobuf:"bytes,51,opt,name=cache_service_url,json=cacheServiceUrl,proto3,oneof" json:"cache_service_url,omitempty"`
	DatabrokerServiceUrl                              *string                   `protobuf:"bytes,52,opt,name=databroker_service_url,json=databrokerServiceUrl,proto3,oneof" json:"databroker_service_url,omitempty"`
	ClientCa                                          *string                   `protobuf:"bytes,53,opt,name=client_ca,json=clientCa,proto3,oneof" json:"client_ca,omitempty"`
	ClientCaFile                                      *string                   `protobuf:"bytes,54,opt,name=client_ca_file,json=clientCaFile,proto3,oneof" json:"client_ca_file,omitempty"`
	ClientCaKeyPairId                                 *string                   `protobuf:"bytes,65,opt,name=client_ca_key_pair_id,json=clientCaKeyPairId,proto3,oneof" json:"client_ca_key_pair_id,omitempty"`
	GoogleCloudServerlessAuthenticationServiceAccount *string                   `protobuf:"bytes,55,opt,name=google_cloud_serverless_authentication_service_account,json=googleCloudServerlessAuthenticationServiceAccount,proto3,oneof" json:"google_cloud_serverless_authentication_service_account,omitempty"`
	Autocert                                          *bool                     `protobuf:"varint,56,opt,name=autocert,proto3,oneof" json:"autocert,omitempty"`
	AutocertUseStaging                                *bool                     `protobuf:"varint,57,opt,name=autocert_use_staging,json=autocertUseStaging,proto3,oneof" json:"autocert_use_staging,omitempty"`
	AutocertMustStaple                                *bool                     `protobuf:"varint,58,opt,name=autocert_must_staple,json=autocertMustStaple,proto3,oneof" json:"autocert_must_staple,omitempty"`
	AutocertDir                                       *string                   `protobuf:"bytes,59,opt,name=autocert_dir,json=autocertDir,proto3,oneof" json:"autocert_dir,omitempty"`
	SkipXffAppend                                     *bool                     `protobuf:"varint,63,opt,name=skip_xff_append,json=skipXffAppend,proto3,oneof" json:"skip_xff_append,omitempty"`
	PrimaryColor                                      *string                   `protobuf:"bytes,69,opt,name=primary_color,json=primaryColor,proto3,oneof" json:"primary_color,omitempty"`
	SecondaryColor                                    *string                   `protobuf:"bytes,70,opt,name=secondary_color,json=secondaryColor,proto3,oneof" json:"secondary_color,omitempty"`
	DarkmodePrimaryColor                              *string                   `protobuf:"bytes,71,opt,name=darkmode_primary_color,json=darkmodePrimaryColor,proto3,oneof" json:"darkmode_primary_color,omitempty"`
	DarkmodeSecondaryColor                            *string                   `protobuf:"bytes,72,opt,name=darkmode_secondary_color,json=darkmodeSecondaryColor,proto3,oneof" json:"darkmode_secondary_color,omitempty"`
	LogoUrl                                           *string                   `protobuf:"bytes,73,opt,name=logo_url,json=logoUrl,proto3,oneof" json:"logo_url,omitempty"`
	FaviconUrl                                        *string                   `protobuf:"bytes,74,opt,name=favicon_url,json=faviconUrl,proto3,oneof" json:"favicon_url,omitempty"`
	ErrorMessageFirstParagraph                        *string                   `protobuf:"bytes,75,opt,name=error_message_first_paragraph,json=errorMessageFirstParagraph,proto3,oneof" json:"error_message_first_paragraph,omitempty"`
	IdentityProvider                                  *string                   `protobuf:"bytes,76,opt,name=identity_provider,json=identityProvider,proto3,oneof" json:"identity_provider,omitempty"`
	IdentityProviderOptions                           *structpb.Struct          `protobuf:"bytes,77,opt,name=identity_provider_options,json=identityProviderOptions,proto3,oneof" json:"identity_provider_options,omitempty"`
	IdentityProviderRefreshInterval                   *durationpb.Duration      `protobuf:"bytes,78,opt,name=identity_provider_refresh_interval,json=identityProviderRefreshInterval,proto3,oneof" json:"identity_provider_refresh_interval,omitempty"`
	IdentityProviderRefreshTimeout                    *durationpb.Duration      `protobuf:"bytes,79,opt,name=identity_provider_refresh_timeout,json=identityProviderRefreshTimeout,proto3,oneof" json:"identity_provider_refresh_timeout,omitempty"`
	AccessLogFields                                   *Settings_StringList      `protobuf:"bytes,82,opt,name=access_log_fields,json=accessLogFields,proto3,oneof" json:"access_log_fields,omitempty"`
	AuthorizeLogFields                                *Settings_StringList      `protobuf:"bytes,83,opt,name=authorize_log_fields,json=authorizeLogFields,proto3,oneof" json:"authorize_log_fields,omitempty"`
	PassIdentityHeaders                               *bool                     `protobuf:"varint,84,opt,name=pass_identity_headers,json=passIdentityHeaders,proto3,oneof" json:"pass_identity_headers,omitempty"`
	OriginatorId                                      string                    `protobuf:"bytes,103,opt,name=originator_id,json=originatorId,proto3" json:"originator_id,omitempty"`
	BearerTokenFormat                                 *BearerTokenFormat        `protobuf:"varint,104,opt,name=bearer_token_format,json=bearerTokenFormat,proto3,enum=pomerium.dashboard.BearerTokenFormat,oneof" json:"bearer_token_format,omitempty"`
	IdpAccessTokenAllowedAudiences                    *Settings_StringList      `protobuf:"bytes,105,opt,name=idp_access_token_allowed_audiences,json=idpAccessTokenAllowedAudiences,proto3,oneof" json:"idp_access_token_allowed_audiences,omitempty"`
	CodecType                                         *CodecType                `protobuf:"varint,109,opt,name=codec_type,json=codecType,proto3,enum=pomerium.dashboard.CodecType,oneof" json:"codec_type,omitempty"`
	CircuitBreakerThresholds                          *CircuitBreakerThresholds `protobuf:"bytes,110,opt,name=circuit_breaker_thresholds,json=circuitBreakerThresholds,proto3,oneof" json:"circuit_breaker_thresholds,omitempty"`
	SshAddress                                        *string                   `protobuf:"bytes,111,opt,name=ssh_address,json=sshAddress,proto3,oneof" json:"ssh_address,omitempty"`
	SshHostKeyFiles                                   *Settings_StringList      `protobuf:"bytes,112,opt,name=ssh_host_key_files,json=sshHostKeyFiles,proto3,oneof" json:"ssh_host_key_files,omitempty"`
	SshHostKeys                                       *Settings_StringList      `protobuf:"bytes,113,opt,name=ssh_host_keys,json=sshHostKeys,proto3,oneof" json:"ssh_host_keys,omitempty"`
	SshUserCaKeyFile                                  *string                   `protobuf:"bytes,114,opt,name=ssh_user_ca_key_file,json=sshUserCaKeyFile,proto3,oneof" json:"ssh_user_ca_key_file,omitempty"`
	SshUserCaKey                                      *string                   `protobuf:"bytes,115,opt,name=ssh_user_ca_key,json=sshUserCaKey,proto3,oneof" json:"ssh_user_ca_key,omitempty"`
	unknownFields                                     protoimpl.UnknownFields
	sizeCache                                         protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{1}
}

func (x *Settings) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Settings) GetClusterId() string {
	if x != nil && x.ClusterId != nil {
		return *x.ClusterId
	}
	return ""
}

func (x *Settings) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *Settings) GetInstallationId() string {
	if x != nil && x.InstallationId != nil {
		return *x.InstallationId
	}
	return ""
}

func (x *Settings) GetLogLevel() string {
	if x != nil && x.LogLevel != nil {
		return *x.LogLevel
	}
	return ""
}

func (x *Settings) GetProxyLogLevel() string {
	if x != nil && x.ProxyLogLevel != nil {
		return *x.ProxyLogLevel
	}
	return ""
}

func (x *Settings) GetSharedSecret() string {
	if x != nil && x.SharedSecret != nil {
		return *x.SharedSecret
	}
	return ""
}

func (x *Settings) GetServices() string {
	if x != nil && x.Services != nil {
		return *x.Services
	}
	return ""
}

func (x *Settings) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *Settings) GetInsecureServer() bool {
	if x != nil && x.InsecureServer != nil {
		return *x.InsecureServer
	}
	return false
}

func (x *Settings) GetDnsFailureRefreshRate() *durationpb.Duration {
	if x != nil {
		return x.DnsFailureRefreshRate
	}
	return nil
}

func (x *Settings) GetDnsLookupFamily() string {
	if x != nil && x.DnsLookupFamily != nil {
		return *x.DnsLookupFamily
	}
	return ""
}

func (x *Settings) GetDnsQueryTimeout() *durationpb.Duration {
	if x != nil {
		return x.DnsQueryTimeout
	}
	return nil
}

func (x *Settings) GetDnsQueryTries() uint32 {
	if x != nil && x.DnsQueryTries != nil {
		return *x.DnsQueryTries
	}
	return 0
}

func (x *Settings) GetDnsRefreshRate() *durationpb.Duration {
	if x != nil {
		return x.DnsRefreshRate
	}
	return nil
}

func (x *Settings) GetDnsUdpMaxQueries() uint32 {
	if x != nil && x.DnsUdpMaxQueries != nil {
		return *x.DnsUdpMaxQueries
	}
	return 0
}

func (x *Settings) GetDnsUseTcp() bool {
	if x != nil && x.DnsUseTcp != nil {
		return *x.DnsUseTcp
	}
	return false
}

func (x *Settings) GetCertificates() []*Settings_Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *Settings) GetHttpRedirectAddr() string {
	if x != nil && x.HttpRedirectAddr != nil {
		return *x.HttpRedirectAddr
	}
	return ""
}

func (x *Settings) GetTimeoutRead() *durationpb.Duration {
	if x != nil {
		return x.TimeoutRead
	}
	return nil
}

func (x *Settings) GetTimeoutWrite() *durationpb.Duration {
	if x != nil {
		return x.TimeoutWrite
	}
	return nil
}

func (x *Settings) GetTimeoutIdle() *durationpb.Duration {
	if x != nil {
		return x.TimeoutIdle
	}
	return nil
}

func (x *Settings) GetAuthenticateServiceUrl() string {
	if x != nil && x.AuthenticateServiceUrl != nil {
		return *x.AuthenticateServiceUrl
	}
	return ""
}

func (x *Settings) GetCookieName() string {
	if x != nil && x.CookieName != nil {
		return *x.CookieName
	}
	return ""
}

func (x *Settings) GetCookieSecret() string {
	if x != nil && x.CookieSecret != nil {
		return *x.CookieSecret
	}
	return ""
}

func (x *Settings) GetCookieDomain() string {
	if x != nil && x.CookieDomain != nil {
		return *x.CookieDomain
	}
	return ""
}

func (x *Settings) GetCookieSecure() bool {
	if x != nil && x.CookieSecure != nil {
		return *x.CookieSecure
	}
	return false
}

func (x *Settings) GetCookieHttpOnly() bool {
	if x != nil && x.CookieHttpOnly != nil {
		return *x.CookieHttpOnly
	}
	return false
}

func (x *Settings) GetCookieSameSite() string {
	if x != nil && x.CookieSameSite != nil {
		return *x.CookieSameSite
	}
	return ""
}

func (x *Settings) GetCookieExpire() *durationpb.Duration {
	if x != nil {
		return x.CookieExpire
	}
	return nil
}

func (x *Settings) GetIdpClientId() string {
	if x != nil && x.IdpClientId != nil {
		return *x.IdpClientId
	}
	return ""
}

func (x *Settings) GetIdpClientSecret() string {
	if x != nil && x.IdpClientSecret != nil {
		return *x.IdpClientSecret
	}
	return ""
}

func (x *Settings) GetIdpProvider() string {
	if x != nil && x.IdpProvider != nil {
		return *x.IdpProvider
	}
	return ""
}

func (x *Settings) GetIdpProviderUrl() string {
	if x != nil && x.IdpProviderUrl != nil {
		return *x.IdpProviderUrl
	}
	return ""
}

func (x *Settings) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *Settings) GetIdpServiceAccount() string {
	if x != nil && x.IdpServiceAccount != nil {
		return *x.IdpServiceAccount
	}
	return ""
}

func (x *Settings) GetIdpRefreshDirectoryTimeout() *durationpb.Duration {
	if x != nil {
		return x.IdpRefreshDirectoryTimeout
	}
	return nil
}

func (x *Settings) GetIdpRefreshDirectoryInterval() *durationpb.Duration {
	if x != nil {
		return x.IdpRefreshDirectoryInterval
	}
	return nil
}

func (x *Settings) GetRequestParams() map[string]string {
	if x != nil {
		return x.RequestParams
	}
	return nil
}

func (x *Settings) GetAuthorizeServiceUrl() string {
	if x != nil && x.AuthorizeServiceUrl != nil {
		return *x.AuthorizeServiceUrl
	}
	return ""
}

func (x *Settings) GetCertificateAuthority() string {
	if x != nil && x.CertificateAuthority != nil {
		return *x.CertificateAuthority
	}
	return ""
}

func (x *Settings) GetCertificateAuthorityFile() string {
	if x != nil && x.CertificateAuthorityFile != nil {
		return *x.CertificateAuthorityFile
	}
	return ""
}

func (x *Settings) GetCertificateAuthorityKeyPairId() string {
	if x != nil && x.CertificateAuthorityKeyPairId != nil {
		return *x.CertificateAuthorityKeyPairId
	}
	return ""
}

func (x *Settings) GetSetResponseHeaders() map[string]string {
	if x != nil {
		return x.SetResponseHeaders
	}
	return nil
}

func (x *Settings) GetJwtClaimsHeaders() map[string]string {
	if x != nil {
		return x.JwtClaimsHeaders
	}
	return nil
}

func (x *Settings) GetJwtGroupsFilter() *JwtGroupsFilter {
	if x != nil {
		return x.JwtGroupsFilter
	}
	return nil
}

func (x *Settings) GetJwtIssuerFormat() IssuerFormat {
	if x != nil && x.JwtIssuerFormat != nil {
		return *x.JwtIssuerFormat
	}
	return IssuerFormat_IssuerHostOnly
}

func (x *Settings) GetDefaultUpstreamTimeout() *durationpb.Duration {
	if x != nil {
		return x.DefaultUpstreamTimeout
	}
	return nil
}

func (x *Settings) GetMetricsAddress() string {
	if x != nil && x.MetricsAddress != nil {
		return *x.MetricsAddress
	}
	return ""
}

func (x *Settings) GetOtelTracesExporter() string {
	if x != nil && x.OtelTracesExporter != nil {
		return *x.OtelTracesExporter
	}
	return ""
}

func (x *Settings) GetOtelTracesSamplerArg() float64 {
	if x != nil && x.OtelTracesSamplerArg != nil {
		return *x.OtelTracesSamplerArg
	}
	return 0
}

func (x *Settings) GetOtelResourceAttributes() []string {
	if x != nil {
		return x.OtelResourceAttributes
	}
	return nil
}

func (x *Settings) GetOtelLogLevel() string {
	if x != nil && x.OtelLogLevel != nil {
		return *x.OtelLogLevel
	}
	return ""
}

func (x *Settings) GetOtelAttributeValueLengthLimit() int32 {
	if x != nil && x.OtelAttributeValueLengthLimit != nil {
		return *x.OtelAttributeValueLengthLimit
	}
	return 0
}

func (x *Settings) GetOtelExporterOtlpEndpoint() string {
	if x != nil && x.OtelExporterOtlpEndpoint != nil {
		return *x.OtelExporterOtlpEndpoint
	}
	return ""
}

func (x *Settings) GetOtelExporterOtlpTracesEndpoint() string {
	if x != nil && x.OtelExporterOtlpTracesEndpoint != nil {
		return *x.OtelExporterOtlpTracesEndpoint
	}
	return ""
}

func (x *Settings) GetOtelExporterOtlpProtocol() string {
	if x != nil && x.OtelExporterOtlpProtocol != nil {
		return *x.OtelExporterOtlpProtocol
	}
	return ""
}

func (x *Settings) GetOtelExporterOtlpTracesProtocol() string {
	if x != nil && x.OtelExporterOtlpTracesProtocol != nil {
		return *x.OtelExporterOtlpTracesProtocol
	}
	return ""
}

func (x *Settings) GetOtelExporterOtlpHeaders() []string {
	if x != nil {
		return x.OtelExporterOtlpHeaders
	}
	return nil
}

func (x *Settings) GetOtelExporterOtlpTracesHeaders() []string {
	if x != nil {
		return x.OtelExporterOtlpTracesHeaders
	}
	return nil
}

func (x *Settings) GetOtelExporterOtlpTimeout() *durationpb.Duration {
	if x != nil {
		return x.OtelExporterOtlpTimeout
	}
	return nil
}

func (x *Settings) GetOtelExporterOtlpTracesTimeout() *durationpb.Duration {
	if x != nil {
		return x.OtelExporterOtlpTracesTimeout
	}
	return nil
}

func (x *Settings) GetOtelBspScheduleDelay() *durationpb.Duration {
	if x != nil {
		return x.OtelBspScheduleDelay
	}
	return nil
}

func (x *Settings) GetOtelBspMaxExportBatchSize() int32 {
	if x != nil && x.OtelBspMaxExportBatchSize != nil {
		return *x.OtelBspMaxExportBatchSize
	}
	return 0
}

func (x *Settings) GetGrpcAddress() string {
	if x != nil && x.GrpcAddress != nil {
		return *x.GrpcAddress
	}
	return ""
}

func (x *Settings) GetGrpcInsecure() bool {
	if x != nil && x.GrpcInsecure != nil {
		return *x.GrpcInsecure
	}
	return false
}

func (x *Settings) GetCacheServiceUrl() string {
	if x != nil && x.CacheServiceUrl != nil {
		return *x.CacheServiceUrl
	}
	return ""
}

func (x *Settings) GetDatabrokerServiceUrl() string {
	if x != nil && x.DatabrokerServiceUrl != nil {
		return *x.DatabrokerServiceUrl
	}
	return ""
}

func (x *Settings) GetClientCa() string {
	if x != nil && x.ClientCa != nil {
		return *x.ClientCa
	}
	return ""
}

func (x *Settings) GetClientCaFile() string {
	if x != nil && x.ClientCaFile != nil {
		return *x.ClientCaFile
	}
	return ""
}

func (x *Settings) GetClientCaKeyPairId() string {
	if x != nil && x.ClientCaKeyPairId != nil {
		return *x.ClientCaKeyPairId
	}
	return ""
}

func (x *Settings) GetGoogleCloudServerlessAuthenticationServiceAccount() string {
	if x != nil && x.GoogleCloudServerlessAuthenticationServiceAccount != nil {
		return *x.GoogleCloudServerlessAuthenticationServiceAccount
	}
	return ""
}

func (x *Settings) GetAutocert() bool {
	if x != nil && x.Autocert != nil {
		return *x.Autocert
	}
	return false
}

func (x *Settings) GetAutocertUseStaging() bool {
	if x != nil && x.AutocertUseStaging != nil {
		return *x.AutocertUseStaging
	}
	return false
}

func (x *Settings) GetAutocertMustStaple() bool {
	if x != nil && x.AutocertMustStaple != nil {
		return *x.AutocertMustStaple
	}
	return false
}

func (x *Settings) GetAutocertDir() string {
	if x != nil && x.AutocertDir != nil {
		return *x.AutocertDir
	}
	return ""
}

func (x *Settings) GetSkipXffAppend() bool {
	if x != nil && x.SkipXffAppend != nil {
		return *x.SkipXffAppend
	}
	return false
}

func (x *Settings) GetPrimaryColor() string {
	if x != nil && x.PrimaryColor != nil {
		return *x.PrimaryColor
	}
	return ""
}

func (x *Settings) GetSecondaryColor() string {
	if x != nil && x.SecondaryColor != nil {
		return *x.SecondaryColor
	}
	return ""
}

func (x *Settings) GetDarkmodePrimaryColor() string {
	if x != nil && x.DarkmodePrimaryColor != nil {
		return *x.DarkmodePrimaryColor
	}
	return ""
}

func (x *Settings) GetDarkmodeSecondaryColor() string {
	if x != nil && x.DarkmodeSecondaryColor != nil {
		return *x.DarkmodeSecondaryColor
	}
	return ""
}

func (x *Settings) GetLogoUrl() string {
	if x != nil && x.LogoUrl != nil {
		return *x.LogoUrl
	}
	return ""
}

func (x *Settings) GetFaviconUrl() string {
	if x != nil && x.FaviconUrl != nil {
		return *x.FaviconUrl
	}
	return ""
}

func (x *Settings) GetErrorMessageFirstParagraph() string {
	if x != nil && x.ErrorMessageFirstParagraph != nil {
		return *x.ErrorMessageFirstParagraph
	}
	return ""
}

func (x *Settings) GetIdentityProvider() string {
	if x != nil && x.IdentityProvider != nil {
		return *x.IdentityProvider
	}
	return ""
}

func (x *Settings) GetIdentityProviderOptions() *structpb.Struct {
	if x != nil {
		return x.IdentityProviderOptions
	}
	return nil
}

func (x *Settings) GetIdentityProviderRefreshInterval() *durationpb.Duration {
	if x != nil {
		return x.IdentityProviderRefreshInterval
	}
	return nil
}

func (x *Settings) GetIdentityProviderRefreshTimeout() *durationpb.Duration {
	if x != nil {
		return x.IdentityProviderRefreshTimeout
	}
	return nil
}

func (x *Settings) GetAccessLogFields() *Settings_StringList {
	if x != nil {
		return x.AccessLogFields
	}
	return nil
}

func (x *Settings) GetAuthorizeLogFields() *Settings_StringList {
	if x != nil {
		return x.AuthorizeLogFields
	}
	return nil
}

func (x *Settings) GetPassIdentityHeaders() bool {
	if x != nil && x.PassIdentityHeaders != nil {
		return *x.PassIdentityHeaders
	}
	return false
}

func (x *Settings) GetOriginatorId() string {
	if x != nil {
		return x.OriginatorId
	}
	return ""
}

func (x *Settings) GetBearerTokenFormat() BearerTokenFormat {
	if x != nil && x.BearerTokenFormat != nil {
		return *x.BearerTokenFormat
	}
	return BearerTokenFormat_BEARER_TOKEN_FORMAT_UNKNOWN
}

func (x *Settings) GetIdpAccessTokenAllowedAudiences() *Settings_StringList {
	if x != nil {
		return x.IdpAccessTokenAllowedAudiences
	}
	return nil
}

func (x *Settings) GetCodecType() CodecType {
	if x != nil && x.CodecType != nil {
		return *x.CodecType
	}
	return CodecType_CODEC_TYPE_UNKNOWN
}

func (x *Settings) GetCircuitBreakerThresholds() *CircuitBreakerThresholds {
	if x != nil {
		return x.CircuitBreakerThresholds
	}
	return nil
}

func (x *Settings) GetSshAddress() string {
	if x != nil && x.SshAddress != nil {
		return *x.SshAddress
	}
	return ""
}

func (x *Settings) GetSshHostKeyFiles() *Settings_StringList {
	if x != nil {
		return x.SshHostKeyFiles
	}
	return nil
}

func (x *Settings) GetSshHostKeys() *Settings_StringList {
	if x != nil {
		return x.SshHostKeys
	}
	return nil
}

func (x *Settings) GetSshUserCaKeyFile() string {
	if x != nil && x.SshUserCaKeyFile != nil {
		return *x.SshUserCaKeyFile
	}
	return ""
}

func (x *Settings) GetSshUserCaKey() string {
	if x != nil && x.SshUserCaKey != nil {
		return *x.SshUserCaKey
	}
	return ""
}

type GetConsoleSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsoleSettingsRequest) Reset() {
	*x = GetConsoleSettingsRequest{}
	mi := &file_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsoleSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsoleSettingsRequest) ProtoMessage() {}

func (x *GetConsoleSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsoleSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetConsoleSettingsRequest) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{2}
}

type GetConsoleSettingsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConsoleSettings *ConsoleSettings       `protobuf:"bytes,1,opt,name=console_settings,json=consoleSettings,proto3" json:"console_settings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConsoleSettingsResponse) Reset() {
	*x = GetConsoleSettingsResponse{}
	mi := &file_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsoleSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsoleSettingsResponse) ProtoMessage() {}

func (x *GetConsoleSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsoleSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetConsoleSettingsResponse) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{3}
}

func (x *GetConsoleSettingsResponse) GetConsoleSettings() *ConsoleSettings {
	if x != nil {
		return x.ConsoleSettings
	}
	return nil
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     *string                `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3,oneof" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{4}
}

func (x *GetSettingsRequest) GetClusterId() string {
	if x != nil && x.ClusterId != nil {
		return *x.ClusterId
	}
	return ""
}

type GetSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *Settings              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	mi := &file_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{5}
}

func (x *GetSettingsResponse) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *Settings              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSettingsRequest) Reset() {
	*x = SetSettingsRequest{}
	mi := &file_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSettingsRequest) ProtoMessage() {}

func (x *SetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSettingsRequest.ProtoReflect.Descriptor instead.
func (*SetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{6}
}

func (x *SetSettingsRequest) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *Settings              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSettingsResponse) Reset() {
	*x = SetSettingsResponse{}
	mi := &file_settings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSettingsResponse) ProtoMessage() {}

func (x *SetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSettingsResponse.ProtoReflect.Descriptor instead.
func (*SetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{7}
}

func (x *SetSettingsResponse) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type Settings_Certificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertBytes     []byte                 `protobuf:"bytes,3,opt,name=cert_bytes,json=certBytes,proto3" json:"cert_bytes,omitempty"`
	KeyBytes      []byte                 `protobuf:"bytes,4,opt,name=key_bytes,json=keyBytes,proto3" json:"key_bytes,omitempty"`
	KeyPairId     string                 `protobuf:"bytes,5,opt,name=key_pair_id,json=keyPairId,proto3" json:"key_pair_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings_Certificate) Reset() {
	*x = Settings_Certificate{}
	mi := &file_settings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings_Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings_Certificate) ProtoMessage() {}

func (x *Settings_Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings_Certificate.ProtoReflect.Descriptor instead.
func (*Settings_Certificate) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Settings_Certificate) GetCertBytes() []byte {
	if x != nil {
		return x.CertBytes
	}
	return nil
}

func (x *Settings_Certificate) GetKeyBytes() []byte {
	if x != nil {
		return x.KeyBytes
	}
	return nil
}

func (x *Settings_Certificate) GetKeyPairId() string {
	if x != nil {
		return x.KeyPairId
	}
	return ""
}

type Settings_StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings_StringList) Reset() {
	*x = Settings_StringList{}
	mi := &file_settings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings_StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings_StringList) ProtoMessage() {}

func (x *Settings_StringList) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings_StringList.ProtoReflect.Descriptor instead.
func (*Settings_StringList) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Settings_StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_settings_proto protoreflect.FileDescriptor

const file_settings_proto_rawDesc = "" +
	"\n" +
	"\x0esettings.proto\x12\x12pomerium.dashboard\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\froutes.proto\"n\n" +
	"\x0fConsoleSettings\x124\n" +
	"\x16enable_feedback_widget\x18\x01 \x01(\bR\x14enableFeedbackWidget\x12%\n" +
	"\x0euse_changesets\x18\x02 \x01(\bR\ruseChangesets\"\xefD\n" +
	"\bSettings\x12\x0e\n" +
	"\x02id\x18k \x01(\tR\x02id\x12\"\n" +
	"\n" +
	"cluster_id\x18l \x01(\tH\x00R\tclusterId\x88\x01\x01\x12;\n" +
	"\vmodified_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12,\n" +
	"\x0finstallation_id\x18D \x01(\tH\x01R\x0einstallationId\x88\x01\x01\x12 \n" +
	"\tlog_level\x18\x03 \x01(\tH\x02R\blogLevel\x88\x01\x01\x12+\n" +
	"\x0fproxy_log_level\x18\x04 \x01(\tH\x03R\rproxyLogLevel\x88\x01\x01\x12(\n" +
	"\rshared_secret\x18\x05 \x01(\tH\x04R\fsharedSecret\x88\x01\x01\x12\x1f\n" +
	"\bservices\x18\x06 \x01(\tH\x05R\bservices\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\a \x01(\tH\x06R\aaddress\x88\x01\x01\x12,\n" +
	"\x0finsecure_server\x18\b \x01(\bH\aR\x0einsecureServer\x88\x01\x01\x12W\n" +
	"\x18dns_failure_refresh_rate\x18x \x01(\v2\x19.google.protobuf.DurationH\bR\x15dnsFailureRefreshRate\x88\x01\x01\x12/\n" +
	"\x11dns_lookup_family\x18< \x01(\tH\tR\x0fdnsLookupFamily\x88\x01\x01\x12J\n" +
	"\x11dns_query_timeout\x18w \x01(\v2\x19.google.protobuf.DurationH\n" +
	"R\x0fdnsQueryTimeout\x88\x01\x01\x12+\n" +
	"\x0fdns_query_tries\x18v \x01(\rH\vR\rdnsQueryTries\x88\x01\x01\x12H\n" +
	"\x10dns_refresh_rate\x18y \x01(\v2\x19.google.protobuf.DurationH\fR\x0ednsRefreshRate\x88\x01\x01\x122\n" +
	"\x13dns_udp_max_queries\x18t \x01(\rH\rR\x10dnsUdpMaxQueries\x88\x01\x01\x12#\n" +
	"\vdns_use_tcp\x18u \x01(\bH\x0eR\tdnsUseTcp\x88\x01\x01\x12L\n" +
	"\fcertificates\x18\t \x03(\v2(.pomerium.dashboard.Settings.CertificateR\fcertificates\x121\n" +
	"\x12http_redirect_addr\x18\n" +
	" \x01(\tH\x0fR\x10httpRedirectAddr\x88\x01\x01\x12A\n" +
	"\ftimeout_read\x18\v \x01(\v2\x19.google.protobuf.DurationH\x10R\vtimeoutRead\x88\x01\x01\x12C\n" +
	"\rtimeout_write\x18\f \x01(\v2\x19.google.protobuf.DurationH\x11R\ftimeoutWrite\x88\x01\x01\x12A\n" +
	"\ftimeout_idle\x18\r \x01(\v2\x19.google.protobuf.DurationH\x12R\vtimeoutIdle\x88\x01\x01\x12=\n" +
	"\x18authenticate_service_url\x18\x0e \x01(\tH\x13R\x16authenticateServiceUrl\x88\x01\x01\x12$\n" +
	"\vcookie_name\x18\x10 \x01(\tH\x14R\n" +
	"cookieName\x88\x01\x01\x12(\n" +
	"\rcookie_secret\x18\x11 \x01(\tH\x15R\fcookieSecret\x88\x01\x01\x12(\n" +
	"\rcookie_domain\x18\x12 \x01(\tH\x16R\fcookieDomain\x88\x01\x01\x12(\n" +
	"\rcookie_secure\x18\x13 \x01(\bH\x17R\fcookieSecure\x88\x01\x01\x12-\n" +
	"\x10cookie_http_only\x18\x14 \x01(\bH\x18R\x0ecookieHttpOnly\x88\x01\x01\x12-\n" +
	"\x10cookie_same_site\x18P \x01(\tH\x19R\x0ecookieSameSite\x88\x01\x01\x12C\n" +
	"\rcookie_expire\x18\x15 \x01(\v2\x19.google.protobuf.DurationH\x1aR\fcookieExpire\x88\x01\x01\x12'\n" +
	"\ridp_client_id\x18\x16 \x01(\tH\x1bR\vidpClientId\x88\x01\x01\x12/\n" +
	"\x11idp_client_secret\x18\x17 \x01(\tH\x1cR\x0fidpClientSecret\x88\x01\x01\x12&\n" +
	"\fidp_provider\x18\x18 \x01(\tH\x1dR\vidpProvider\x88\x01\x01\x12-\n" +
	"\x10idp_provider_url\x18\x19 \x01(\tH\x1eR\x0eidpProviderUrl\x88\x01\x01\x12\x16\n" +
	"\x06scopes\x18\x1a \x03(\tR\x06scopes\x123\n" +
	"\x13idp_service_account\x18\x1b \x01(\tH\x1fR\x11idpServiceAccount\x88\x01\x01\x12a\n" +
	"\x1didp_refresh_directory_timeout\x18\x1c \x01(\v2\x19.google.protobuf.DurationH R\x1aidpRefreshDirectoryTimeout\x88\x01\x01\x12c\n" +
	"\x1eidp_refresh_directory_interval\x18\x1d \x01(\v2\x19.google.protobuf.DurationH!R\x1bidpRefreshDirectoryInterval\x88\x01\x01\x12V\n" +
	"\x0erequest_params\x18\x1e \x03(\v2/.pomerium.dashboard.Settings.RequestParamsEntryR\rrequestParams\x127\n" +
	"\x15authorize_service_url\x18  \x01(\tH\"R\x13authorizeServiceUrl\x88\x01\x01\x128\n" +
	"\x15certificate_authority\x18\" \x01(\tH#R\x14certificateAuthority\x88\x01\x01\x12A\n" +
	"\x1acertificate_authority_file\x18# \x01(\tH$R\x18certificateAuthorityFile\x88\x01\x01\x12M\n" +
	"!certificate_authority_key_pair_id\x18@ \x01(\tH%R\x1dcertificateAuthorityKeyPairId\x88\x01\x01\x12f\n" +
	"\x14set_response_headers\x18C \x03(\v24.pomerium.dashboard.Settings.SetResponseHeadersEntryR\x12setResponseHeaders\x12`\n" +
	"\x12jwt_claims_headers\x18B \x03(\v22.pomerium.dashboard.Settings.JwtClaimsHeadersEntryR\x10jwtClaimsHeaders\x12O\n" +
	"\x11jwt_groups_filter\x18W \x01(\v2#.pomerium.dashboard.JwtGroupsFilterR\x0fjwtGroupsFilter\x12Q\n" +
	"\x11jwt_issuer_format\x18j \x01(\x0e2 .pomerium.dashboard.IssuerFormatH&R\x0fjwtIssuerFormat\x88\x01\x01\x12X\n" +
	"\x18default_upstream_timeout\x18' \x01(\v2\x19.google.protobuf.DurationH'R\x16defaultUpstreamTimeout\x88\x01\x01\x12,\n" +
	"\x0fmetrics_address\x18( \x01(\tH(R\x0emetricsAddress\x88\x01\x01\x125\n" +
	"\x14otel_traces_exporter\x18X \x01(\tH)R\x12otelTracesExporter\x88\x01\x01\x12:\n" +
	"\x17otel_traces_sampler_arg\x18Y \x01(\x01H*R\x14otelTracesSamplerArg\x88\x01\x01\x128\n" +
	"\x18otel_resource_attributes\x18Z \x03(\tR\x16otelResourceAttributes\x12)\n" +
	"\x0eotel_log_level\x18[ \x01(\tH+R\fotelLogLevel\x88\x01\x01\x12M\n" +
	"!otel_attribute_value_length_limit\x18\\ \x01(\x05H,R\x1dotelAttributeValueLengthLimit\x88\x01\x01\x12B\n" +
	"\x1botel_exporter_otlp_endpoint\x18] \x01(\tH-R\x18otelExporterOtlpEndpoint\x88\x01\x01\x12O\n" +
	"\"otel_exporter_otlp_traces_endpoint\x18^ \x01(\tH.R\x1eotelExporterOtlpTracesEndpoint\x88\x01\x01\x12B\n" +
	"\x1botel_exporter_otlp_protocol\x18_ \x01(\tH/R\x18otelExporterOtlpProtocol\x88\x01\x01\x12O\n" +
	"\"otel_exporter_otlp_traces_protocol\x18` \x01(\tH0R\x1eotelExporterOtlpTracesProtocol\x88\x01\x01\x12;\n" +
	"\x1aotel_exporter_otlp_headers\x18a \x03(\tR\x17otelExporterOtlpHeaders\x12H\n" +
	"!otel_exporter_otlp_traces_headers\x18b \x03(\tR\x1dotelExporterOtlpTracesHeaders\x12[\n" +
	"\x1aotel_exporter_otlp_timeout\x18c \x01(\v2\x19.google.protobuf.DurationH1R\x17otelExporterOtlpTimeout\x88\x01\x01\x12h\n" +
	"!otel_exporter_otlp_traces_timeout\x18d \x01(\v2\x19.google.protobuf.DurationH2R\x1dotelExporterOtlpTracesTimeout\x88\x01\x01\x12U\n" +
	"\x17otel_bsp_schedule_delay\x18e \x01(\v2\x19.google.protobuf.DurationH3R\x14otelBspScheduleDelay\x88\x01\x01\x12F\n" +
	"\x1eotel_bsp_max_export_batch_size\x18f \x01(\x05H4R\x19otelBspMaxExportBatchSize\x88\x01\x01\x12&\n" +
	"\fgrpc_address\x18. \x01(\tH5R\vgrpcAddress\x88\x01\x01\x12(\n" +
	"\rgrpc_insecure\x18/ \x01(\bH6R\fgrpcInsecure\x88\x01\x01\x12/\n" +
	"\x11cache_service_url\x183 \x01(\tH7R\x0fcacheServiceUrl\x88\x01\x01\x129\n" +
	"\x16databroker_service_url\x184 \x01(\tH8R\x14databrokerServiceUrl\x88\x01\x01\x12 \n" +
	"\tclient_ca\x185 \x01(\tH9R\bclientCa\x88\x01\x01\x12)\n" +
	"\x0eclient_ca_file\x186 \x01(\tH:R\fclientCaFile\x88\x01\x01\x125\n" +
	"\x15client_ca_key_pair_id\x18A \x01(\tH;R\x11clientCaKeyPairId\x88\x01\x01\x12v\n" +
	"6google_cloud_serverless_authentication_service_account\x187 \x01(\tH<R1googleCloudServerlessAuthenticationServiceAccount\x88\x01\x01\x12\x1f\n" +
	"\bautocert\x188 \x01(\bH=R\bautocert\x88\x01\x01\x125\n" +
	"\x14autocert_use_staging\x189 \x01(\bH>R\x12autocertUseStaging\x88\x01\x01\x125\n" +
	"\x14autocert_must_staple\x18: \x01(\bH?R\x12autocertMustStaple\x88\x01\x01\x12&\n" +
	"\fautocert_dir\x18; \x01(\tH@R\vautocertDir\x88\x01\x01\x12+\n" +
	"\x0fskip_xff_append\x18? \x01(\bHAR\rskipXffAppend\x88\x01\x01\x12(\n" +
	"\rprimary_color\x18E \x01(\tHBR\fprimaryColor\x88\x01\x01\x12,\n" +
	"\x0fsecondary_color\x18F \x01(\tHCR\x0esecondaryColor\x88\x01\x01\x129\n" +
	"\x16darkmode_primary_color\x18G \x01(\tHDR\x14darkmodePrimaryColor\x88\x01\x01\x12=\n" +
	"\x18darkmode_secondary_color\x18H \x01(\tHER\x16darkmodeSecondaryColor\x88\x01\x01\x12\x1e\n" +
	"\blogo_url\x18I \x01(\tHFR\alogoUrl\x88\x01\x01\x12$\n" +
	"\vfavicon_url\x18J \x01(\tHGR\n" +
	"faviconUrl\x88\x01\x01\x12F\n" +
	"\x1derror_message_first_paragraph\x18K \x01(\tHHR\x1aerrorMessageFirstParagraph\x88\x01\x01\x120\n" +
	"\x11identity_provider\x18L \x01(\tHIR\x10identityProvider\x88\x01\x01\x12X\n" +
	"\x19identity_provider_options\x18M \x01(\v2\x17.google.protobuf.StructHJR\x17identityProviderOptions\x88\x01\x01\x12k\n" +
	"\"identity_provider_refresh_interval\x18N \x01(\v2\x19.google.protobuf.DurationHKR\x1fidentityProviderRefreshInterval\x88\x01\x01\x12i\n" +
	"!identity_provider_refresh_timeout\x18O \x01(\v2\x19.google.protobuf.DurationHLR\x1eidentityProviderRefreshTimeout\x88\x01\x01\x12X\n" +
	"\x11access_log_fields\x18R \x01(\v2'.pomerium.dashboard.Settings.StringListHMR\x0faccessLogFields\x88\x01\x01\x12^\n" +
	"\x14authorize_log_fields\x18S \x01(\v2'.pomerium.dashboard.Settings.StringListHNR\x12authorizeLogFields\x88\x01\x01\x127\n" +
	"\x15pass_identity_headers\x18T \x01(\bHOR\x13passIdentityHeaders\x88\x01\x01\x12#\n" +
	"\roriginator_id\x18g \x01(\tR\foriginatorId\x12Z\n" +
	"\x13bearer_token_format\x18h \x01(\x0e2%.pomerium.dashboard.BearerTokenFormatHPR\x11bearerTokenFormat\x88\x01\x01\x12x\n" +
	"\"idp_access_token_allowed_audiences\x18i \x01(\v2'.pomerium.dashboard.Settings.StringListHQR\x1eidpAccessTokenAllowedAudiences\x88\x01\x01\x12A\n" +
	"\n" +
	"codec_type\x18m \x01(\x0e2\x1d.pomerium.dashboard.CodecTypeHRR\tcodecType\x88\x01\x01\x12o\n" +
	"\x1acircuit_breaker_thresholds\x18n \x01(\v2,.pomerium.dashboard.CircuitBreakerThresholdsHSR\x18circuitBreakerThresholds\x88\x01\x01\x12$\n" +
	"\vssh_address\x18o \x01(\tHTR\n" +
	"sshAddress\x88\x01\x01\x12Y\n" +
	"\x12ssh_host_key_files\x18p \x01(\v2'.pomerium.dashboard.Settings.StringListHUR\x0fsshHostKeyFiles\x88\x01\x01\x12P\n" +
	"\rssh_host_keys\x18q \x01(\v2'.pomerium.dashboard.Settings.StringListHVR\vsshHostKeys\x88\x01\x01\x123\n" +
	"\x14ssh_user_ca_key_file\x18r \x01(\tHWR\x10sshUserCaKeyFile\x88\x01\x01\x12*\n" +
	"\x0fssh_user_ca_key\x18s \x01(\tHXR\fsshUserCaKey\x88\x01\x01\x1ai\n" +
	"\vCertificate\x12\x1d\n" +
	"\n" +
	"cert_bytes\x18\x03 \x01(\fR\tcertBytes\x12\x1b\n" +
	"\tkey_bytes\x18\x04 \x01(\fR\bkeyBytes\x12\x1e\n" +
	"\vkey_pair_id\x18\x05 \x01(\tR\tkeyPairId\x1a$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\x1a@\n" +
	"\x12RequestParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\x17SetResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15JwtClaimsHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_cluster_idB\x12\n" +
	"\x10_installation_idB\f\n" +
	"\n" +
	"_log_levelB\x12\n" +
	"\x10_proxy_log_levelB\x10\n" +
	"\x0e_shared_secretB\v\n" +
	"\t_servicesB\n" +
	"\n" +
	"\b_addressB\x12\n" +
	"\x10_insecure_serverB\x1b\n" +
	"\x19_dns_failure_refresh_rateB\x14\n" +
	"\x12_dns_lookup_familyB\x14\n" +
	"\x12_dns_query_timeoutB\x12\n" +
	"\x10_dns_query_triesB\x13\n" +
	"\x11_dns_refresh_rateB\x16\n" +
	"\x14_dns_udp_max_queriesB\x0e\n" +
	"\f_dns_use_tcpB\x15\n" +
	"\x13_http_redirect_addrB\x0f\n" +
	"\r_timeout_readB\x10\n" +
	"\x0e_timeout_writeB\x0f\n" +
	"\r_timeout_idleB\x1b\n" +
	"\x19_authenticate_service_urlB\x0e\n" +
	"\f_cookie_nameB\x10\n" +
	"\x0e_cookie_secretB\x10\n" +
	"\x0e_cookie_domainB\x10\n" +
	"\x0e_cookie_secureB\x13\n" +
	"\x11_cookie_http_onlyB\x13\n" +
	"\x11_cookie_same_siteB\x10\n" +
	"\x0e_cookie_expireB\x10\n" +
	"\x0e_idp_client_idB\x14\n" +
	"\x12_idp_client_secretB\x0f\n" +
	"\r_idp_providerB\x13\n" +
	"\x11_idp_provider_urlB\x16\n" +
	"\x14_idp_service_accountB \n" +
	"\x1e_idp_refresh_directory_timeoutB!\n" +
	"\x1f_idp_refresh_directory_intervalB\x18\n" +
	"\x16_authorize_service_urlB\x18\n" +
	"\x16_certificate_authorityB\x1d\n" +
	"\x1b_certificate_authority_fileB$\n" +
	"\"_certificate_authority_key_pair_idB\x14\n" +
	"\x12_jwt_issuer_formatB\x1b\n" +
	"\x19_default_upstream_timeoutB\x12\n" +
	"\x10_metrics_addressB\x17\n" +
	"\x15_otel_traces_exporterB\x1a\n" +
	"\x18_otel_traces_sampler_argB\x11\n" +
	"\x0f_otel_log_levelB$\n" +
	"\"_otel_attribute_value_length_limitB\x1e\n" +
	"\x1c_otel_exporter_otlp_endpointB%\n" +
	"#_otel_exporter_otlp_traces_endpointB\x1e\n" +
	"\x1c_otel_exporter_otlp_protocolB%\n" +
	"#_otel_exporter_otlp_traces_protocolB\x1d\n" +
	"\x1b_otel_exporter_otlp_timeoutB$\n" +
	"\"_otel_exporter_otlp_traces_timeoutB\x1a\n" +
	"\x18_otel_bsp_schedule_delayB!\n" +
	"\x1f_otel_bsp_max_export_batch_sizeB\x0f\n" +
	"\r_grpc_addressB\x10\n" +
	"\x0e_grpc_insecureB\x14\n" +
	"\x12_cache_service_urlB\x19\n" +
	"\x17_databroker_service_urlB\f\n" +
	"\n" +
	"_client_caB\x11\n" +
	"\x0f_client_ca_fileB\x18\n" +
	"\x16_client_ca_key_pair_idB9\n" +
	"7_google_cloud_serverless_authentication_service_accountB\v\n" +
	"\t_autocertB\x17\n" +
	"\x15_autocert_use_stagingB\x17\n" +
	"\x15_autocert_must_stapleB\x0f\n" +
	"\r_autocert_dirB\x12\n" +
	"\x10_skip_xff_appendB\x10\n" +
	"\x0e_primary_colorB\x12\n" +
	"\x10_secondary_colorB\x19\n" +
	"\x17_darkmode_primary_colorB\x1b\n" +
	"\x19_darkmode_secondary_colorB\v\n" +
	"\t_logo_urlB\x0e\n" +
	"\f_favicon_urlB \n" +
	"\x1e_error_message_first_paragraphB\x14\n" +
	"\x12_identity_providerB\x1c\n" +
	"\x1a_identity_provider_optionsB%\n" +
	"#_identity_provider_refresh_intervalB$\n" +
	"\"_identity_provider_refresh_timeoutB\x14\n" +
	"\x12_access_log_fieldsB\x17\n" +
	"\x15_authorize_log_fieldsB\x18\n" +
	"\x16_pass_identity_headersB\x16\n" +
	"\x14_bearer_token_formatB%\n" +
	"#_idp_access_token_allowed_audiencesB\r\n" +
	"\v_codec_typeB\x1d\n" +
	"\x1b_circuit_breaker_thresholdsB\x0e\n" +
	"\f_ssh_addressB\x15\n" +
	"\x13_ssh_host_key_filesB\x10\n" +
	"\x0e_ssh_host_keysB\x17\n" +
	"\x15_ssh_user_ca_key_fileB\x12\n" +
	"\x10_ssh_user_ca_keyJ\x04\b\x0f\x10\x10J\x04\b)\x10*J\x04\b*\x10+J\x04\bU\x10VJ\x04\bV\x10W\"\x1b\n" +
	"\x19GetConsoleSettingsRequest\"l\n" +
	"\x1aGetConsoleSettingsResponse\x12N\n" +
	"\x10console_settings\x18\x01 \x01(\v2#.pomerium.dashboard.ConsoleSettingsR\x0fconsoleSettings\"G\n" +
	"\x12GetSettingsRequest\x12\"\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tH\x00R\tclusterId\x88\x01\x01B\r\n" +
	"\v_cluster_id\"O\n" +
	"\x13GetSettingsResponse\x128\n" +
	"\bsettings\x18\x01 \x01(\v2\x1c.pomerium.dashboard.SettingsR\bsettings\"N\n" +
	"\x12SetSettingsRequest\x128\n" +
	"\bsettings\x18\x01 \x01(\v2\x1c.pomerium.dashboard.SettingsR\bsettings\"O\n" +
	"\x13SetSettingsResponse\x128\n" +
	"\bsettings\x18\x01 \x01(\v2\x1c.pomerium.dashboard.SettingsR\bsettings*z\n" +
	"\tCodecType\x12\x16\n" +
	"\x12CODEC_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fCODEC_TYPE_AUTO\x10\x01\x12\x14\n" +
	"\x10CODEC_TYPE_HTTP1\x10\x02\x12\x14\n" +
	"\x10CODEC_TYPE_HTTP2\x10\x03\x12\x14\n" +
	"\x10CODEC_TYPE_HTTP3\x10\x042\xae\x03\n" +
	"\x0fSettingsService\x12^\n" +
	"\vGetSettings\x12&.pomerium.dashboard.GetSettingsRequest\x1a'.pomerium.dashboard.GetSettingsResponse\x12^\n" +
	"\vSetSettings\x12&.pomerium.dashboard.SetSettingsRequest\x1a'.pomerium.dashboard.SetSettingsResponse\x12f\n" +
	"\x13GetBrandingSettings\x12&.pomerium.dashboard.GetSettingsRequest\x1a'.pomerium.dashboard.GetSettingsResponse\x12s\n" +
	"\x12GetConsoleSettings\x12-.pomerium.dashboard.GetConsoleSettingsRequest\x1a..pomerium.dashboard.GetConsoleSettingsResponseB-Z+github.com/pomerium/pomerium-console/pkg/pbb\x06proto3"

var (
	file_settings_proto_rawDescOnce sync.Once
	file_settings_proto_rawDescData []byte
)

func file_settings_proto_rawDescGZIP() []byte {
	file_settings_proto_rawDescOnce.Do(func() {
		file_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settings_proto_rawDesc), len(file_settings_proto_rawDesc)))
	})
	return file_settings_proto_rawDescData
}

var file_settings_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_settings_proto_goTypes = []any{
	(CodecType)(0),                     // 0: pomerium.dashboard.CodecType
	(*ConsoleSettings)(nil),            // 1: pomerium.dashboard.ConsoleSettings
	(*Settings)(nil),                   // 2: pomerium.dashboard.Settings
	(*GetConsoleSettingsRequest)(nil),  // 3: pomerium.dashboard.GetConsoleSettingsRequest
	(*GetConsoleSettingsResponse)(nil), // 4: pomerium.dashboard.GetConsoleSettingsResponse
	(*GetSettingsRequest)(nil),         // 5: pomerium.dashboard.GetSettingsRequest
	(*GetSettingsResponse)(nil),        // 6: pomerium.dashboard.GetSettingsResponse
	(*SetSettingsRequest)(nil),         // 7: pomerium.dashboard.SetSettingsRequest
	(*SetSettingsResponse)(nil),        // 8: pomerium.dashboard.SetSettingsResponse
	(*Settings_Certificate)(nil),       // 9: pomerium.dashboard.Settings.Certificate
	(*Settings_StringList)(nil),        // 10: pomerium.dashboard.Settings.StringList
	nil,                                // 11: pomerium.dashboard.Settings.RequestParamsEntry
	nil,                                // 12: pomerium.dashboard.Settings.SetResponseHeadersEntry
	nil,                                // 13: pomerium.dashboard.Settings.JwtClaimsHeadersEntry
	(*timestamppb.Timestamp)(nil),      // 14: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 15: google.protobuf.Duration
	(*JwtGroupsFilter)(nil),            // 16: pomerium.dashboard.JwtGroupsFilter
	(IssuerFormat)(0),                  // 17: pomerium.dashboard.IssuerFormat
	(*structpb.Struct)(nil),            // 18: google.protobuf.Struct
	(BearerTokenFormat)(0),             // 19: pomerium.dashboard.BearerTokenFormat
	(*CircuitBreakerThresholds)(nil),   // 20: pomerium.dashboard.CircuitBreakerThresholds
}
var file_settings_proto_depIdxs = []int32{
	14, // 0: pomerium.dashboard.Settings.modified_at:type_name -> google.protobuf.Timestamp
	15, // 1: pomerium.dashboard.Settings.dns_failure_refresh_rate:type_name -> google.protobuf.Duration
	15, // 2: pomerium.dashboard.Settings.dns_query_timeout:type_name -> google.protobuf.Duration
	15, // 3: pomerium.dashboard.Settings.dns_refresh_rate:type_name -> google.protobuf.Duration
	9,  // 4: pomerium.dashboard.Settings.certificates:type_name -> pomerium.dashboard.Settings.Certificate
	15, // 5: pomerium.dashboard.Settings.timeout_read:type_name -> google.protobuf.Duration
	15, // 6: pomerium.dashboard.Settings.timeout_write:type_name -> google.protobuf.Duration
	15, // 7: pomerium.dashboard.Settings.timeout_idle:type_name -> google.protobuf.Duration
	15, // 8: pomerium.dashboard.Settings.cookie_expire:type_name -> google.protobuf.Duration
	15, // 9: pomerium.dashboard.Settings.idp_refresh_directory_timeout:type_name -> google.protobuf.Duration
	15, // 10: pomerium.dashboard.Settings.idp_refresh_directory_interval:type_name -> google.protobuf.Duration
	11, // 11: pomerium.dashboard.Settings.request_params:type_name -> pomerium.dashboard.Settings.RequestParamsEntry
	12, // 12: pomerium.dashboard.Settings.set_response_headers:type_name -> pomerium.dashboard.Settings.SetResponseHeadersEntry
	13, // 13: pomerium.dashboard.Settings.jwt_claims_headers:type_name -> pomerium.dashboard.Settings.JwtClaimsHeadersEntry
	16, // 14: pomerium.dashboard.Settings.jwt_groups_filter:type_name -> pomerium.dashboard.JwtGroupsFilter
	17, // 15: pomerium.dashboard.Settings.jwt_issuer_format:type_name -> pomerium.dashboard.IssuerFormat
	15, // 16: pomerium.dashboard.Settings.default_upstream_timeout:type_name -> google.protobuf.Duration
	15, // 17: pomerium.dashboard.Settings.otel_exporter_otlp_timeout:type_name -> google.protobuf.Duration
	15, // 18: pomerium.dashboard.Settings.otel_exporter_otlp_traces_timeout:type_name -> google.protobuf.Duration
	15, // 19: pomerium.dashboard.Settings.otel_bsp_schedule_delay:type_name -> google.protobuf.Duration
	18, // 20: pomerium.dashboard.Settings.identity_provider_options:type_name -> google.protobuf.Struct
	15, // 21: pomerium.dashboard.Settings.identity_provider_refresh_interval:type_name -> google.protobuf.Duration
	15, // 22: pomerium.dashboard.Settings.identity_provider_refresh_timeout:type_name -> google.protobuf.Duration
	10, // 23: pomerium.dashboard.Settings.access_log_fields:type_name -> pomerium.dashboard.Settings.StringList
	10, // 24: pomerium.dashboard.Settings.authorize_log_fields:type_name -> pomerium.dashboard.Settings.StringList
	19, // 25: pomerium.dashboard.Settings.bearer_token_format:type_name -> pomerium.dashboard.BearerTokenFormat
	10, // 26: pomerium.dashboard.Settings.idp_access_token_allowed_audiences:type_name -> pomerium.dashboard.Settings.StringList
	0,  // 27: pomerium.dashboard.Settings.codec_type:type_name -> pomerium.dashboard.CodecType
	20, // 28: pomerium.dashboard.Settings.circuit_breaker_thresholds:type_name -> pomerium.dashboard.CircuitBreakerThresholds
	10, // 29: pomerium.dashboard.Settings.ssh_host_key_files:type_name -> pomerium.dashboard.Settings.StringList
	10, // 30: pomerium.dashboard.Settings.ssh_host_keys:type_name -> pomerium.dashboard.Settings.StringList
	1,  // 31: pomerium.dashboard.GetConsoleSettingsResponse.console_settings:type_name -> pomerium.dashboard.ConsoleSettings
	2,  // 32: pomerium.dashboard.GetSettingsResponse.settings:type_name -> pomerium.dashboard.Settings
	2,  // 33: pomerium.dashboard.SetSettingsRequest.settings:type_name -> pomerium.dashboard.Settings
	2,  // 34: pomerium.dashboard.SetSettingsResponse.settings:type_name -> pomerium.dashboard.Settings
	5,  // 35: pomerium.dashboard.SettingsService.GetSettings:input_type -> pomerium.dashboard.GetSettingsRequest
	7,  // 36: pomerium.dashboard.SettingsService.SetSettings:input_type -> pomerium.dashboard.SetSettingsRequest
	5,  // 37: pomerium.dashboard.SettingsService.GetBrandingSettings:input_type -> pomerium.dashboard.GetSettingsRequest
	3,  // 38: pomerium.dashboard.SettingsService.GetConsoleSettings:input_type -> pomerium.dashboard.GetConsoleSettingsRequest
	6,  // 39: pomerium.dashboard.SettingsService.GetSettings:output_type -> pomerium.dashboard.GetSettingsResponse
	8,  // 40: pomerium.dashboard.SettingsService.SetSettings:output_type -> pomerium.dashboard.SetSettingsResponse
	6,  // 41: pomerium.dashboard.SettingsService.GetBrandingSettings:output_type -> pomerium.dashboard.GetSettingsResponse
	4,  // 42: pomerium.dashboard.SettingsService.GetConsoleSettings:output_type -> pomerium.dashboard.GetConsoleSettingsResponse
	39, // [39:43] is the sub-list for method output_type
	35, // [35:39] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_settings_proto_init() }
func file_settings_proto_init() {
	if File_settings_proto != nil {
		return
	}
	file_routes_proto_init()
	file_settings_proto_msgTypes[1].OneofWrappers = []any{}
	file_settings_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settings_proto_rawDesc), len(file_settings_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settings_proto_goTypes,
		DependencyIndexes: file_settings_proto_depIdxs,
		EnumInfos:         file_settings_proto_enumTypes,
		MessageInfos:      file_settings_proto_msgTypes,
	}.Build()
	File_settings_proto = out.File
	file_settings_proto_goTypes = nil
	file_settings_proto_depIdxs = nil
}
