name: Dependabot

on:
  pull_request:

jobs:
  generate:
    if: ${{ github.actor == 'dependabot[bot]' }}
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ github.head_ref }}
          submodules: "true"
          token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}

      - name: Generate
        run: make generate

      - name: Commit
        uses: devops-infra/action-commit-push@f01d24007c469639f252dc88109ef96bfbff33db
        with:
          github_token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
          commit_message: "dependabot: generate"

  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    name: Build
    needs: generate
    uses: ./.github/workflows/reusable-build.yaml
    with:
      ref: ${{ github.head_ref }}
